export const MASTER_INDIA_TOURISM_DIRECTORY: Record<string, {
  Name: string;
  City: string;
  State: string;
  Type: string;
  image_url: string;
  weather: string;
  bestTime: string;
  packing: string;
  budget: string;
  history_geo_political: string;
  picnic_spots: string;
  transport_roadmap: string;
  hotels_booking: string;
  markets_food: string;
  culture_helpline: string;
}> = {
  "kedarnath": {
    Name: "Kedarnath Temple - Sacred Himalayan Shrine",
    City: "Kedarnath", State: "Uttarakhand", Type: "🛕 Char Dham & Jyotirlinga",
    image_url: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=1200&q=80",
    weather: "❄️ 5°C to 15°C (Cold)", bestTime: "May to June & September to October",
    packing: "🧳 Heavy woolens, thermal innerwear, trekking shoes, waterproof jacket, walking stick.",
    budget: "💰 Est. Budget: ₹3,000 - ₹6,000 / day",
    history_geo_political: "History: Built by the Pandavas and revived by Adi Shankaracharya in the 8th century. Situated near the Mandakini river.",
    picnic_spots: "🛕 Kedarnath Main Temple\n🏛️ Bhairavnath Temple\n🌿 Vasuki Tal Trek\n🏞️ Chorabari Glacier (Gandhi Sarovar)",
    transport_roadmap: "Road Map: Accessible via Gaurikund trek (16 km) or helicopter service from Phata/Sersi. Transport: Dehradun Airport (DED) & Rishikesh Railway Station.",
    hotels_booking: "🏨 GMVN Tourist Transit Camps\n🏨 Kedar Camp Resorts\n🏨 Local Pilgrim Cottages",
    markets_food: "🛍️ Kedarnath Base Market.\n🍲 Hot Maggi, Tea, Local Rajma Chawal, Satvik North Indian Thali.",
    culture_helpline: "Culture: Himalayan spiritual traditions. Helpline: Police: 100 | SOS: 112"
  },
  "badrinath": {
    Name: "Badrinath Temple - Abode of Lord Vishnu",
    City: "Badrinath", State: "Uttarakhand", Type: "🛕 Char Dham Pilgrimage",
    image_url: "https://images.unsplash.com/photo-1590736969955-71cc94901144?auto=format&fit=crop&w=1200&q=80",
    weather: "⛅ 8°C to 18°C (Chilly)", bestTime: "May to June & September to October",
    packing: "🧳 Heavy woolens, warm jackets, thermal layers, comfortable trekking shoes.",
    budget: "💰 Est. Budget: ₹2,500 - ₹5,500 / day",
    history_geo_political: "History: Re-established as a major holy shrine by Adi Shankaracharya in the 9th century, nestled between Nar and Narayan mountain ranges.",
    picnic_spots: "🛕 Badrinath Temple\n🏛️ Tapt Kund (Hot Sulphur Springs)\n🌿 Mana Village (Last village of India)\n🏞️ Vasudhara Falls & Charanpaduka",
    transport_roadmap: "Road Map: Connected via NH-7. Transport: Rishikesh Railway Station (295 km) & Dehradun Airport (315 km).",
    hotels_booking: "🏨 Sarovar Portico Badrinath\n🏨 Hotel Snow Crest\n🏨 GMVN Guest House Badrinath",
    markets_food: "🛍️ Badrinath Main Bazaar.\n🍲 North Indian Sattvic Food, Local Tea, Jalebi.",
    culture_helpline: "Culture: Vedic Vaishnavism. Helpline: Police: 100 | SOS: 112"
  },
  "gangotri": {
    Name: "Gangotri Dham - Origin of River Ganga",
    City: "Gangotri", State: "Uttarakhand", Type: "🛕 Char Dham Pilgrimage",
    image_url: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80",
    weather: "🌡️ 6°C to 17°C", bestTime: "May to June & September to October",
    packing: "🧳 Woolen clothes, windcheater, sturdy walking boots.",
    budget: "💰 Est. Budget: ₹2,000 - ₹4,500 / day",
    history_geo_political: "History: Dedicated to Goddess Ganga, built on the banks of Bhagirathi river where King Bhagirath worshipped Lord Shiva.",
    picnic_spots: "🛕 Gangotri Temple\n🏛️ Bhagirath Shila\n🌿 Gaumukh Glacier Trek (Source)\n🏞️ Subhidyal Waterfall",
    transport_roadmap: "Road Map: Connected via NH-34. Transport: Dehradun Airport (250 km) & Rishikesh Railway Station.",
    hotels_booking: "🏨 GMVN Tourist Rest House\n🏨 Hotel Bhagirathi\n🏨 Local Pilgrim Lodges",
    markets_food: "🛍️ Gangotri Market Square.\n🍲 Pure Vegetarian North Indian Meals, Hot Soups.",
    culture_helpline: "Culture: River goddess worship. Helpline: Police: 100 | SOS: 112"
  },
  "yamunotri": {
    Name: "Yamunotri Dham - Source of River Yamuna",
    City: "Yamunotri", State: "Uttarakhand", Type: "🛕 Char Dham Pilgrimage",
    image_url: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80",
    weather: "🌡️ 5°C to 16°C", bestTime: "May to June & September to October",
    packing: "🧳 Woolens, raincoat, trekking shoes, walking stick.",
    budget: "💰 Est. Budget: ₹2,000 - ₹4,500 / day",
    history_geo_political: "History: Westernmost shrine of the Garhwal Himalayas, dedicated to Goddess Yamuna, featuring natural thermal springs.",
    picnic_spots: "🛕 Yamunotri Temple\n🏛️ Surya Kund (Hot Water Spring)\n🌿 Divya Shila\n🏞️ Saptarishi Kund Trek",
    transport_roadmap: "Road Map: Accessible via Jankichatti trek (6 km). Transport: Dehradun Airport (180 km).",
    hotels_booking: "🏨 GMVN Yamunotri\n🏨 Hotel Yamuna Kriti\n🏨 Pilgrim Camps",
    markets_food: "🛍️ Jankichatti & Yamunotri Stalls.\n🍲 Local Tea, Potatoes boiled in Surya Kund, Simple Thali.",
    culture_helpline: "Culture: Himalayan ritual heritage. Helpline: Police: 100 | SOS: 112"
  },
  "somnath": {
    Name: "Somnath Temple - First Among Jyotirlingas",
    City: "Prabhas Patan (Veraval)", State: "Gujarat", Type: "🛕 First Jyotirlinga",
    image_url: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=1200&q=80",
    weather: "☀️ 32°C (Coastal Breeze)", bestTime: "October to March",
    packing: "🧳 Light cotton clothing, traditional wear for temple inner sanctum.",
    budget: "💰 Est. Budget: ₹2,000 - ₹4,500 / day",
    history_geo_political: "History: The first of the 12 Jyotirlinga shrines of Shiva. Rebuilt several times throughout history as a symbol of eternal faith.",
    picnic_spots: "🛕 Somnath Temple & Sound-Light Show\n🏛️ Bhalka Tirth (Lord Krishna's departure site)\n🌿 Triveni Sangam (Sea confluence)\n🏞️ Prabhas Patan Museum",
    transport_roadmap: "Road Map: Connected via NH-51. Transport: Veraval Railway Station (7 km) & Diu Airport (55 km).",
    hotels_booking: "🏨 The Fern Residency Somnath\n🏨 Lords Inn Somnath\n🏨 Hotel Somnath Sagar",
    markets_food: "🛍️ Somnath Temple Chowk.\n🍲 Gujarati Thali, Khaman, Ganthiya, Coconut Water.",
    culture_helpline: "Culture: Saurashtra cultural heritage. Helpline: Police: 100 | SOS: 112"
  },
  "mahakaleshwar": {
    Name: "Mahakaleshwar Ujjain - Shrine of Time & Power",
    City: "Ujjain", State: "Madhya Pradesh", Type: "🛕 Famous Jyotirlinga",
    image_url: "https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?auto=format&fit=crop&w=1200&q=80",
    weather: "🌤️ 25°C to 38°C", bestTime: "October to March (Sawan & Mahashivratri are grand)",
    packing: "🧳 Traditional dhoti/kurta for Bhasma Aarti, light cottons for day.",
    budget: "💰 Est. Budget: ₹1,800 - ₹4,000 / day",
    history_geo_political: "History: Ancient temple situated alongside the holy Kshipra river, famous worldwide for its unique Bhasma Aarti ritual.",
    picnic_spots: "🛕 Mahakaleshwar Jyotirlinga & Mahakal Lok Corridor\n🏛️ Harsiddhi Temple & Kal Bhairav Temple\n🌿 Ram Ghat (Kshipra River Aarti)\n🏞️ Sandipani Ashram",
    transport_roadmap: "Road Map: Connected via Indore-Ujjain highway. Transport: Ujjain Junction & Indore Airport (IDR, 55 km).",
    hotels_booking: "🏨 Hotel Anjushree Ujjain\n🏨 Hotel Imperial Grand\n🏨 Ujjain Darshan Hotel",
    markets_food: "🛍️ Mahakal Market, Freeganj.\n🍲 Malwa Poha, Bhutte ka Kees, Ujjaini Kachori.",
    culture_helpline: "Culture: Ancient Avanti spiritual traditions. Helpline: Police: 100 | SOS: 112"
  },
  "shirdi": {
    Name: "Shirdi Sai Baba Shrine - Home of Universal Faith",
    City: "Shirdi", State: "Maharashtra", Type: "🛕 Revered Spiritual Shrine",
    image_url: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=1200&q=80",
    weather: "🌤️ 28°C to 38°C", bestTime: "October to March",
    packing: "🧳 Simple traditional or comfortable casual clothing.",
    budget: "💰 Est. Budget: ₹1,500 - ₹3,500 / day",
    history_geo_political: "History: Sacred town where Saint Sai Baba lived and preached universal love, tolerance, and devotion.",
    picnic_spots: "🛕 Shri Sai Baba Sansthan Temple Complex\n🏛️ Dwarkamai Masjid & Chavadi\n🌿 Gurusthan & Sai Museum\n🏞️ Wet N Joy Water Park (Nearby)",
    transport_roadmap: "Road Map: Connected via Ahmednagar-Manmad highway. Transport: Sainagar Shirdi Railway Station & Shirdi Airport (SAG).",
    hotels_booking: "🏨 Sun-n-Sand Shirdi\n🏨 Hotel Sai Leela\n🏨 Marasa Sarovar Premiere Shirdi",
    markets_food: "🛍️ Temple Road Prasad Market.\n🍲 Maharashtrian Thali, Puran Poli, Laddoos.",
    culture_helpline: "Culture: Secular saint devotion. Helpline: Police: 100 | SOS: 112"
  },
  "tirupati": {
    Name: "Tirupati - Abode of Lord Venkateswara",
    City: "Tirupati", State: "Andhra Pradesh", Type: "🛕 Richest Spiritual Shrine",
    image_url: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80",
    weather: "☀️ 32°C (Warm)", bestTime: "September to March",
    packing: "🧳 Traditional Indian attire (Dhoti/Kurta for men, Saree/Salwar for women).",
    budget: "💰 Est. Budget: ₹2,000 - ₹4,500 / day",
    history_geo_political: "History: World-renowned temple town nestled in the Seshachalam Hills.",
    picnic_spots: "🛕 Sri Venkateswara Swami Temple (Tirumala Hills - The supreme and richest pilgrimage shrine in the world)\n🏛️ Govindaraja Swamy Temple & Alamelu Mangapuram (Tiruchanur)\n🌿 Sri Venkateswara Zoological Park & Silathoranam (Natural rock arch)\n🏞️ Akasaganga Waterfalls",
    transport_roadmap: "Road Map: Connected via NH-716. Transport: Tirupati Main Station & TIR Airport.",
    hotels_booking: "🏨 Fortune Select Grand Ridge\n🏨 Marasa Sarovar Premiere\n🏨 Hotel Bliss",
    markets_food: "🛍️ Tirumala Bazaar, Municipal Market.\n🍲 World famous Tirupati Laddu Prasadam, Andhra Meals.",
    culture_helpline: "Culture: Ancient Hindu devotional heritage. Helpline: Police: 100 | SOS: 112"
  },
  "rameswaram": {
    Name: "Rameshwaram - Sacred Island & Jyotirlinga",
    City: "Rameshwaram", State: "Tamil Nadu", Type: "🛕 Char Dham & Jyotirlinga",
    image_url: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80",
    weather: "☀️ 31°C (Tropical Coastal)", bestTime: "October to April",
    packing: "🧳 Light cotton clothes, traditional wear, extra pair of clothes for holy water bath (Theertham).",
    budget: "💰 Est. Budget: ₹2,000 - ₹4,000 / day",
    history_geo_political: "History: Sacred island town where Lord Rama built a bridge across the sea to Lanka. Home to Ramanathaswamy Temple featuring the longest corridor among Indian temples.",
    picnic_spots: "🛕 Ramanathaswamy Temple & 22 Holy Theerthams (Wells)\n🏛️ Pamban Bridge (India's first sea bridge)\n🌿 Dhanushkodi Beach & Ghost Town (End of the land)\n🏞️ Dr. A.P.J. Abdul Kalam Memorial",
    transport_roadmap: "Road Map: Connected via NH-87 and Pamban Bridge. Transport: Rameswaram Railway Station & Madurai Airport (170 km).",
    hotels_booking: "🏨 Hotel Tamil Nadu Rameswaram\n🏨 Daiwik Hotels Rameswaram\n🏨 Hotel Rameshwaram Grand",
    markets_food: "🛍️ Temple Car Street Bazaar, Fish market (for locals).\n🍲 South Indian Filter Coffee, Idli-Dosa, Chettinad Meals.",
    culture_helpline: "Culture: Ancient Dravidian temple architecture. Helpline: Police: 100 | SOS: 112"
  },
  "varanasi": {
    Name: "Varanasi (Kashi) - Spiritual Capital of India",
    City: "Varanasi", State: "Uttar Pradesh", Type: "🛕 Ancient Jyotirlinga City",
    image_url: "https://images.unsplash.com/photo-1561359313-0639aad49ff6?auto=format&fit=crop&w=1200&q=80",
    weather: "🌤️ 28°C to 38°C", bestTime: "October to March",
    packing: "🧳 Light cottons in summer, light woolens in winter, comfortable walking footwear.",
    budget: "💰 Est. Budget: ₹1,800 - ₹4,000 / day",
    history_geo_political: "History: One of the oldest living cities in the world, situated on the banks of River Ganga. Famous for Kashi Vishwanath Jyotirlinga and spiritual ghats.",
    picnic_spots: "🛕 Kashi Vishwanath Temple & Kashi Vishwanath Corridor\n🏛️ Dashashwamedh Ghat (Grand Ganga Aarti)\n🌿 Sarnath (Where Buddha gave his first sermon)\n🏞️ Assi Ghat & Boat Ride on River Ganges",
    transport_roadmap: "Road Map: Well connected via national highways. Transport: Varanasi Junction (BSB) & Lal Bahadur Shastri International Airport (VNS).",
    hotels_booking: "🏨 BrijRama Palace Varanasi\n🏨 Taj Ganges Varanasi\n🏨 Hotel Suryauday Haveli",
    markets_food: "🛍️ Godowla Chowk, Thatheri Bazaar.\n🍲 Banarasi Paan, Kachori Jalebi, Tamatar Chaat, Malaiyyo.",
    culture_helpline: "Culture: Ancient Hindu Vedic culture & classical arts. Helpline: Police: 100 | SOS: 112"
  },
  "khatushyam": {
    Name: "Khatu Shyam Ji - Abode of Shyam Baba",
    City: "Khatu", State: "Rajasthan", Type: "🛕 Devotional Shrine",
    image_url: "https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?auto=format&fit=crop&w=1200&q=80",
    weather: "☀️ 30°C to 40°C (Warm & Dry)", bestTime: "October to March (Falgun Mela is grand)",
    packing: "🧳 Traditional or comfortable cotton clothes, woolen stoles in winter.",
    budget: "💰 Est. Budget: ₹1,500 - ₹3,500 / day",
    history_geo_political: "History: Highly revered shrine dedicated to Barbarika (Shyam Baba), who is worshipped as an avatar of Krishna in Kaliyuga.",
    picnic_spots: "🛕 Khatu Shyam Ji Main Temple\n🏛️ Shyam Kund (Sacred pond)\n🌿 Shyam Vatika & Suraj Kund\n🏞️ Ringas Local Market",
    transport_roadmap: "Road Map: Connected via Jaipur-Bikaner highway. Transport: Ringas Junction (17 km) & Jaipur Airport (80 km).",
    hotels_booking: "🏨 Hotel Shyam Residency\n🏨 Shri Shyam Sarovar\n🏨 Local Pilgrim Dharamshalas",
    markets_food: "🛍️ Temple Street Bazaar.\n🍲 Rajasthani Dal Baati Churma, Peda Prasad, Mirchi Bada.",
    culture_helpline: "Culture: Marwari devotional traditions. Helpline: Police: 100 | SOS: 112"
  },
  "salasar": {
    Name: "Salasar Balaji - Shrine of Lord Hanuman",
    City: "Salasar", State: "Rajasthan", Type: "🛕 Sacred Hanuman Temple",
    image_url: "https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?auto=format&fit=crop&w=1200&q=80",
    weather: "☀️ 32°C (Dry & Warm)", bestTime: "October to March",
    packing: "🧳 Simple traditional clothing, comfortable footwear.",
    budget: "💰 Est. Budget: ₹1,500 - ₹3,000 / day",
    history_geo_political: "History: One of the most famous temples dedicated to Lord Hanuman, featuring a unique idol with a beard and mustache.",
    picnic_spots: "🛕 Salasar Balaji Main Temple\n🏛️ Anjani Mata Temple (Mother of Hanuman)\n🌿 Mohan Dham\n🏞️ Local Salasar Town Bazaar",
    transport_roadmap: "Road Map: Connected via Sujangarh-Salasar road. Transport: Sujangarh Railway Station (25 km).",
    hotels_booking: "🏨 Hotel Anjani\n🏨 Bhawani Niketan\n🏨 Local Dharamshalas",
    markets_food: "🛍️ Salasar Market.\n🍲 Besan Ke Gatte, Traditional Rajasthani Thali, Churma.",
    culture_helpline: "Culture: Rajasthani folk devotion. Helpline: Police: 100 | SOS: 112"
  },
  "pushkar_brahma": {
    Name: "Brahma Temple Pushkar - Unique Creator Shrine",
    City: "Pushkar", State: "Rajasthan", Type: "🛕 Rare Brahma Temple",
    image_url: "https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?auto=format&fit=crop&w=1200&q=80",
    weather: "🌤️ 25°C to 35°C", bestTime: "October to March (Pushkar Camel Fair time)",
    packing: "🧳 Light cottons, comfortable slip-on shoes for temple ghats.",
    budget: "💰 Est. Budget: ₹1,800 - ₹4,000 / day",
    history_geo_political: "History: One of the very few existing temples dedicated to Lord Brahma in the world, situated beside the holy Pushkar Lake.",
    picnic_spots: "🛕 Brahma Temple Pushkar\n🏛️ Pushkar Lake & Varaha Ghat (Evening Aarti)\n🌿 Savitri Temple (On Ratnagiri hill top)\n🏞️ Rangji Temple",
    transport_roadmap: "Road Map: Connected via Ajmer-Pushkar road. Transport: Ajmer Junction (15 km) & Kishangarh Airport (40 km).",
    hotels_booking: "🏨 The Westin Pushkar Resort & Spa\n🏨 Hotel Brahma Horizon\n🏨 Pushkar Bagh",
    markets_food: "🛍️ Brahma Temple Road Bazaar, Main Market.\n🍲 Malpua of Pushkar, Falooda, Cafe vegan food, Dal Baati.",
    culture_helpline: "Culture: Spiritual temple town vibe. Helpline: Police: 100 | SOS: 112"
  },
  "eklingji": {
    Name: "Eklingji Temple - Historic Deity of Mewar",
    City: "Kailashnagar (Udaipur)", State: "Rajasthan", Type: "🛕 Historic Shiva Temple",
    image_url: "https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?auto=format&fit=crop&w=1200&q=80",
    weather: "🌤️ 26°C to 36°C", bestTime: "September to March",
    packing: "🧳 Decent traditional clothing required inside the temple premises.",
    budget: "💰 Est. Budget: ₹2,000 - ₹4,500 / day",
    history_geo_political: "History: Double-storied magnificent temple complex built in 734 AD by Bappa Rawal, dedicated to Lord Shiva (Eklingji), the ruling deity of Mewar rulers.",
    picnic_spots: "🛕 Eklingji Temple Complex (108 temples inside)\n🏛️ Sas-Bahu Temples Nagda (Ancient ruins nearby)\n🌿 Baghela Lake view\n🏞️ Nagda Ancient Village",
    transport_roadmap: "Road Map: Located 22 km north of Udaipur on NH-8. Transport: Udaipur City Station & Maharana Pratap Airport (UDR).",
    hotels_booking: "🏨 Raffles Udaipur (Nearby)\n🏨 Aurika Udaipur\n🏨 Local Heritage Stays",
    markets_food: "🛍️ Nagda Road Stalls.\n🍲 Mewari Dal Baati, Mirchi Bada, Traditional Sweets.",
    culture_helpline: "Culture: Royal Mewar heritage. Helpline: Police: 100 | SOS: 112"
  },
  "mehandipur": {
    Name: "Mehandipur Balaji - Mystical Healing Shrine",
    City: "Mehandipur", State: "Rajasthan", Type: "🛕 Spiritual Exorcism & Faith Shrine",
    image_url: "https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?auto=format&fit=crop&w=1200&q=80",
    weather: "☀️ 32°C (Warm)", bestTime: "October to March",
    packing: "🧳 Simple traditional clothes, strict rules regarding prasad and temple rituals.",
    budget: "💰 Est. Budget: ₹1,200 - ₹3,000 / day",
    history_geo_political: "History: Prominent temple dedicated to Lord Hanuman, widely visited for spiritual healing and faith-based rituals.",
    picnic_spots: "🛕 Mehandipur Balaji Main Temple\n🏛️ Pret Raj Sarkar Temple\n🌿 Bhairav Ji Temple\n🏞️ Local Town Market",
    transport_roadmap: "Road Map: Situated on Jaipur-Agra National Highway-21. Transport: Bandikui Junction (35 km) & Jaipur Airport (95 km).",
    hotels_booking: "🏨 Hotel Balaji Darshan\n🏨 Pilgrim Guest Houses",
    markets_food: "🛍️ Balaji Chowk Market.\n🍲 Simple North Indian Sattvic Food, Boondi Prasad.",
    culture_helpline: "Culture: Faith-based spiritual customs. Helpline: Police: 100 | SOS: 112"
  },
  "dwarka": {
    Name: "Dwarkadhish Temple - Kingdom of Lord Krishna",
    City: "Dwarka", State: "Gujarat", Type: "🛕 Char Dham & Ancient Shrine",
    image_url: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=1200&q=80",
    weather: "☀️ 30°C (Coastal Breeze)", bestTime: "October to March",
    packing: "🧳 Light cotton clothing, traditional temple attire, sunglasses.",
    budget: "💰 Est. Budget: ₹2,000 - ₹4,500 / day",
    history_geo_political: "History: Ancient coastal city believed to be the legendary capital kingdom of Lord Krishna. One of the sacred Char Dhams.",
    picnic_spots: "🛕 Dwarkadhish Temple (Jagat Mandir)\n🏛️ Sudama Setu & Gomti Ghat\n🌿 Nageshwar Jyotirlinga (Nearby)\n🏞️ Bet Dwarka Island & Marine National Park",
    transport_roadmap: "Road Map: Connected via NH-51. Transport: Dwarka Railway Station & Jamnagar Airport (130 km).",
    hotels_booking: "🏨 Goverdhan Green Resort Dwarka\n🏨 Hotel Lord's Inn Dwarka\n🏨 Hotel Vraj Inn",
    markets_food: "🛍️ Dwarka Market, Bhadra Chowk.\n🍲 Gujarati Thali, Fafda Jalebi, Dwarkadhish Sukhdi Prasad.",
    culture_helpline: "Culture: Pushtimarg & Krishna devotion. Helpline: Police: 100 | SOS: 112"
  },
  "akshardham_gandhinagar": {
    Name: "Akshardham Gandhinagar - Architectural Marvel",
    City: "Gandhinagar", State: "Gujarat", Type: "🛕 Cultural & Spiritual Complex",
    image_url: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=1200&q=80",
    weather: "🌤️ 28°C to 38°C", bestTime: "October to March",
    packing: "🧳 Decent modest clothing, comfortable walking shoes.",
    budget: "💰 Est. Budget: ₹2,000 - ₹4,000 / day",
    history_geo_political: "History: Grand spiritual-cultural monument built by BAPS Swaminarayan Sanstha, showcasing traditional Indian art and values.",
    picnic_spots: "🛕 Akshardham Mandir Main Monument\n🏛️ Sat-Chit-Anand Water Show (Evening fountain show)\n🌿 Abhishek Mandap & Garden walks\n🏞️ Indroda Nature Park (Nearby)",
    transport_roadmap: "Road Map: Connected via Sarkhej-Gandhinagar Highway. Transport: Ahmedabad Railway Station & Sardar Vallabhbhai Patel International Airport (AMD, 20 km).",
    hotels_booking: "🏨 The Leela Gandhinagar\n🏨 GIFT City Club - Members Only / Hotel\n🏨 Hotel Sentosa",
    markets_food: "🛍️ Premvati Food Parlour inside complex.\n🍲 Swaminarayan Sattvic Thali, Dhokla, Gujarati Farsan.",
    culture_helpline: "Culture: Swaminarayan spiritual heritage. Helpline: Police: 100 | SOS: 112"
  },
  "ambaji": {
    Name: "Ambaji Temple - Premier Shakti Peeth",
    City: "Ambaji", State: "Gujarat", Type: "🛕 Holy Shakti Peeth",
    image_url: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=1200&q=80",
    weather: "🍃 24°C to 34°C", bestTime: "September to March (Bhadra Purnima Mela is huge)",
    packing: "🧳 Traditional or comfortable cotton wear, light jacket for evenings.",
    budget: "💰 Est. Budget: ₹1,500 - ₹3,500 / day",
    history_geo_political: "History: One of the 51 Shakti Peeths of Goddess Amba. Notably, the main shrine contains no physical idol, only a sacred Shri Yantra.",
    picnic_spots: "🛕 Ambaji Temple Main Shrine\n🏛️ Gabbar Hill (Original seat of Goddess via ropeway or steps)\n🌿 Mansarovar Lake\n🏞️ Kamakshi Mandir",
    transport_roadmap: "Road Map: Connected via Palanpur-Ambaji road. Transport: Abu Road Railway Station (20 km) & Ahmedabad Airport (180 km).",
    hotels_booking: "🏨 Hotel Ambaji International\n🏨 Toran Tourist Bungalow Ambaji\n🏨 Hotel Sheetal",
    markets_food: "🛍️ Ambaji Temple Market Street.\n🍲 Gujarati Thali, Khaman, Mohanthal Prasad.",
    culture_helpline: "Culture: Devi worship traditions. Helpline: Police: 100 | SOS: 112"
  },
  "modhera_sun": {
    Name: "Modhera Sun Temple - Ancient Solanki Architecture",
    City: "Modhera", State: "Gujarat", Type: "🛕 Historical Sun Temple",
    image_url: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=1200&q=80",
    weather: "☀️ 31°C (Warm)", bestTime: "October to March (Annual Modhera Dance Festival in Jan)",
    packing: "🧳 Light clothing, sunglasses, hat, comfortable walking shoes.",
    budget: "💰 Est. Budget: ₹1,500 - ₹3,000 / day",
    history_geo_political: "History: Magnificent 11th-century temple dedicated to the Sun God, built by King Bhimdev I of the Solanki dynasty on the Pushpavati river.",
    picnic_spots: "🛕 Modhera Sun Temple Complex\n🏛️ Surya Kund (Stepped water tank with 108 miniature shrines)\n🌿 Sabhamandap (Hall with 52 intricately carved pillars)\n🏞️ Archaeological Museum",
    transport_roadmap: "Road Map: Located 25 km from Mehsana via SH-41. Transport: Mehsana Railway Station & Ahmedabad Airport (100 km).",
    hotels_booking: "🏨 The Palms Resort Mehsana\n🏨 Local Heritage Hotels",
    markets_food: "🛍️ Modhera Town Stalls.\n🍲 Traditional Gujarati Snacks, Ganthiya, Tea.",
    culture_helpline: "Culture: Solanki architectural heritage. Helpline: Police: 100 | SOS: 112"
  },
  "dakor": {
    Name: "Dakor (Ranchhodji Temple) - Holy Krishna Shrine",
    City: "Dakor", State: "Gujarat", Type: "🛕 Renowned Vaishnav Shrine",
    image_url: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=1200&q=80",
    weather: "☀️ 32°C (Warm)", bestTime: "October to March (Purnima days have huge gatherings)",
    packing: "🧳 Simple traditional clothing, comfortable footwear.",
    budget: "💰 Est. Budget: ₹1,200 - ₹2,800 / day",
    history_geo_political: "History: Famous temple dedicated to Ranchhodji (a form of Lord Krishna), highly revered by devotees across Gujarat.",
    picnic_spots: "🛕 Ranchhodji Maharaj Temple Complex\n🏛️ Gomti Lake Ghats and Boating\n🌿 Dakor Town Bazaar\n🏞️ Laxminarayan Temple",
    transport_roadmap: "Road Map: Connected via Nadiad-Modasa road. Transport: Dakor Railway Station & Vadodara Airport (55 km).",
    hotels_booking: "🏨 Hotel Krishna Palace Dakor\n🏨 Pilgrim Dharamshalas",
    markets_food: "🛍️ Dakor Temple Road Market.\n🍲 Famous Dakor Gota, Sev Mamra, Peda Prasad.",
    culture_helpline: "Culture: Bhakti movement heritage. Helpline: Police: 100 | SOS: 112"
  },
  "siddhivinayak": {
    Name: "Shree Siddhivinayak Temple - Revered Ganesha Shrine",
    City: "Mumbai", State: "Maharashtra", Type: "🛕 Famous Ganesha Temple",
    image_url: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=1200&q=80",
    weather: "🌴 30°C (Coastal Humid)", bestTime: "November to February",
    packing: "🧳 Light cotton clothing, traditional temple wear, comfortable footwear for queues.",
    budget: "💰 Est. Budget: ₹2,000 - ₹4,500 / day",
    history_geo_political: "History: One of the richest and most famous Ganesha temples in India, built in the late 18th century in Mumbai.",
    picnic_spots: "🛕 Siddhivinayak Ganpati Temple\n🏛️ Prabhadevi Beach & Worli Sea Face\n🌿 Shivaji Park Promenade\n🏞️ Dadar Chowpatty",
    transport_roadmap: "Road Map: Well connected via city local trains and cabs. Transport: Dadar Railway Station & Chhatrapati Shivaji Maharaj International Airport (BOM).",
    hotels_booking: "🏨 The St. Regis Mumbai\n🏨 Four Seasons Hotel Mumbai\n🏨 Hotel City Point",
    markets_food: "🛍️ Dadar West Market, Flower Market.\n🍲 Mumbai Street Food, Vada Pav, Modak, South Indian Snacks.",
    culture_helpline: "Culture: Vibrant Maharashtrian cultural hub. Helpline: Police: 100 | SOS: 112"
  },
  "trimbakeshwar": {
    Name: "Trimbakeshwar Shiva Temple - Source of Godavari",
    City: "Trimbak (Nashik)", State: "Maharashtra", Type: "🛕 Ancient Jyotirlinga Shrine",
    image_url: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=1200&q=80",
    weather: "🍃 22°C to 32°C (Pleasant Hills)", bestTime: "October to March",
    packing: "🧳 Traditional dhoti/kurta for inner sanctum rituals, light woolens for evenings.",
    budget: "💰 Est. Budget: ₹1,800 - ₹4,000 / day",
    history_geo_political: "History: An ancient Jyotirlinga temple situated at the foot of Brahamagiri mountain, where the sacred Godavari River originates.",
    picnic_spots: "🛕 Trimbakeshwar Jyotirlinga Temple\n🏛️ Brahmagiri Hills Trek (Origin of Godavari)\n🌿 Kushavarta Kund (Sacred bathing tank)\n🏞️ Anjneri Hills (Birthplace of Lord Hanuman)",
    transport_roadmap: "Road Map: Connected via Nashik-Trimbak road (28 km from Nashik). Transport: Nashik Road Railway Station & Ozar Airport (Nashik).",
    hotels_booking: "🏨 Hotel Trimbak Palace\n🏨 Anand Resort Trimbak\n🏨 MTDC Holiday Resort Trimbak",
    markets_food: "🛍️ Trimbak Town Bazaar.\n🍲 Maharashtrian Thali, Misal Pav, Pithla Bhakri.",
    culture_helpline: "Culture: Vedic rituals and pitru pujas. Helpline: Police: 100 | SOS: 112"
  },
  "dagdusheth": {
    Name: "Shreemant Dagdusheth Halwai Ganpati - Beloved Pune Deity",
    City: "Pune", State: "Maharashtra", Type: "🛕 Historic Ganesha Shrine",
    image_url: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=1200&q=80",
    weather: "🌤️ 25°C to 35°C", bestTime: "August to March (Ganeshotsav is world-famous)",
    packing: "🧳 Comfortable casuals or traditional clothes.",
    budget: "💰 Est. Budget: ₹1,800 - ₹4,000 / day",
    history_geo_political: "History: Highly revered Ganesha temple established over a century ago in the heart of Pune city by sweets vendor Dagdusheth Halwai.",
    picnic_spots: "🛕 Dagdusheth Ganpati Temple\n🏛️ Shaniwar Wada Fort (Historic Peshwa seat)\n🌿 Lal Mahal & Kasba Peth\n🏞️ Saras Baug & Ganpati Temple",
    transport_roadmap: "Road Map: Located centrally in Budhwar Peth, Pune. Transport: Pune Junction Railway Station & Pune International Airport (PNQ).",
    hotels_booking: "🏨 JW Marriott Hotel Pune\n🏨 Hotel Aurora Towers\n🏨 Hotel Ranjeet",
    markets_food: "🛍️ Laxmi Road Bazaar, Tulsi Baug.\n🍲 Puneri Misal Pav, Mastani Milkshake, Bakarwadi.",
    culture_helpline: "Culture: Maratha heritage and festivities. Helpline: Police: 100 | SOS: 112"
  },
  "tuljabhavani": {
    Name: "Tulja Bhavani Temple - Guardian Goddess of Marathas",
    City: "Tuljapur (Dharashiv)", State: "Maharashtra", Type: "🛕 Sacred Shakti Peeth",
    image_url: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=1200&q=80",
    weather: "☀️ 30°C to 38°C", bestTime: "October to March",
    packing: "🧳 Traditional Indian attire, comfortable walking shoes.",
    budget: "💰 Est. Budget: ₹1,500 - ₹3,500 / day",
    history_geo_political: "History: Historic temple dedicated to Goddess Bhavani, revered as the patron deity of Chhatrapati Shivaji Maharaj and the Maratha empire.",
    picnic_spots: "🛕 Tulja Bhavani Main Temple Complex\n🏛️ Yamai Devi Temple & Ghats\n🌿 Chintamani Ganpati Temple\n🏞️ Fort of Ghatshila",
    transport_roadmap: "Road Map: Connected via Solapur-Tuljapur highway. Transport: Solapur Railway Station (45 km).",
    hotels_booking: "🏨 MTDC Holiday Resort Tuljapur\n🏨 Local Pilgrim Lodges & Hotels",
    markets_food: "🛍️ Temple Approach Market.\n🍲 Jowar Bhakri, Zunka, Maharashtrian Thali.",
    culture_helpline: "Culture: Maratha martial heritage & devotion. Helpline: Police: 100 | SOS: 112"
  },
  "grishneshwar": {
    Name: "Grishneshwar Jyotirlinga - Last of the 12 Jyotirlingas",
    City: "Verul (Aurangabad/Chhatrapati Sambhajinagar)", State: "Maharashtra", Type: "🛕 Ancient Jyotirlinga",
    image_url: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=1200&q=80",
    weather: "☀️ 28°C to 38°C", bestTime: "October to March",
    packing: "🧳 Light cotton clothing, traditional temple attire, sunglasses.",
    budget: "💰 Est. Budget: ₹1,800 - ₹4,000 / day",
    history_geo_political: "History: An ancient Shiva temple located right next to the world-famous Ellora Caves. Regarded as the last of the 12 Jyotirlingas.",
    picnic_spots: "🛕 Grishneshwar Jyotirlinga Temple\n🏛️ Ellora Caves (UNESCO World Heritage rock-cut architecture)\n🌿 Bhadra Maruti Temple (Khuldabad)\n🏞️ Daulatabad Fort (Devagiri)",
    transport_roadmap: "Road Map: Located 30 km from Chhatrapati Sambhajinagar via Ellora road. Transport: Aurangabad Railway Station & Aurangabad Airport (IXU).",
    hotels_booking: "🏨 Welcomhotel by ITC Hotels, Aurangabad\n🏨 Lemon Tree Hotel Aurangabad\n🏨 MTDC Ellora Resort",
    markets_food: "🛍️ Ellora Handicraft Stalls, Local Town Market.\n🍲 Hyderabadi-influenced Maharashtrian Cuisine, Naan Qalia, Puran Poli.",
    culture_helpline: "Culture: Deccan historical and architectural heritage. Helpline: Police: 100 | SOS: 112"
  },
  "bankebihari_vrindavan": {
    Name: "Banke Bihari Temple - Divine Shrine of Vrindavan",
    City: "Vrindavan", State: "Uttar Pradesh", Type: "🛕 Renowned Krishna Shrine",
    image_url: "https://images.unsplash.com/photo-1561359313-0639aad49ff6?auto=format&fit=crop&w=1200&q=80",
    weather: "🌤️ 22°C to 38°C", bestTime: "October to March (Janmashtami & Holi are vibrant)",
    packing: "🧳 Traditional or modest cotton clothing, comfortable footwear (shoes are often left outside far from temple).",
    budget: "💰 Est. Budget: ₹1,500 - ₹3,500 / day",
    history_geo_political: "History: One of the most revered and visited temples of Lord Krishna in Vrindavan, known for its unique 'Jhulan Yatra' and curtain-darshan tradition.",
    picnic_spots: "🛕 Banke Bihari Temple & Prem Mandir\n🏛️ ISKCON Temple Vrindavan & Radharamana Temple\n🌿 Nidhivan & Seva Kunj\n🏞️ Keshi Ghat Yamuna Aarti",
    transport_roadmap: "Road Map: Connected via NH-19 (Delhi-Agra Highway). Transport: Mathura Junction Railway Station (12 km) & Agra Airport (65 km).",
    hotels_booking: "🏨 Nidhivan Sarovar Portico Vrindavan\n🏨 Hotel Ananda Krishna Dham\n🏨 MVT Guesthouse Vrindavan",
    markets_food: "🛍️ Loi Bazaar, Banke Bihari Gali.\n🍲 Mathura ke Pede, Rabri, Kachori Jalebi, Chaat.",
    culture_helpline: "Culture: Brij Bhasha devotional culture. Helpline: Police: 100 | SOS: 112"
  },
  "ayodhya_ram_mandir": {
    Name: "Ayodhya Ram Mandir - Birthplace of Lord Rama",
    City: "Ayodhya", State: "Uttar Pradesh", Type: "🛕 Grand Historic Temple",
    image_url: "https://images.unsplash.com/photo-1561359313-0639aad49ff6?auto=format&fit=crop&w=1200&q=80",
    weather: "🌤️ 24°C to 38°C", bestTime: "October to March (Deepotsav is legendary)",
    packing: "🧳 Traditional Indian wear, comfortable walking footwear for large temple corridors.",
    budget: "💰 Est. Budget: ₹1,800 - ₹4,000 / day",
    history_geo_political: "History: The magnificent newly constructed grand temple at the sacred birth site of Lord Rama in Ayodhya along the Sarayu River.",
    picnic_spots: "🛕 Ayodhya Ram Mandir & Hanumangarhi Temple\n🏛️ Kanak Bhavan & Sita ki Rasoi\n🌿 Sarayu River Ghats (Ram ki Paidi Aarti)\n🏞️ Guptar Ghat",
    transport_roadmap: "Road Map: Connected via NH-27. Transport: Ayodhya Dham Junction Railway Station & Maharishi Valmiki International Airport Ayodhya (AYJ).",
    hotels_booking: "🏨 Ramada by Wyndham Ayodhya\n🏨 Hotel Krishna Palace\n🏨 Abhay Mandapam",
    markets_food: "🛍️ Ram Path Market, Chowk Bazaar.\n🍲 Ayodhya ke Laddu Prasad, Rabri Malai, North Indian Thali.",
    culture_helpline: "Culture: Sanatan Vedic heritage. Helpline: Police: 100 | SOS: 112"
  },
  "vindhyavasini": {
    Name: "Vindhyachal Shakti Peeth - Abode of Goddess Vindhyavasini",
    City: "Vindhyachal (Mirzapur)", State: "Uttar Pradesh", Type: "🛕 Powerful Shakti Peeth",
    image_url: "https://images.unsplash.com/photo-1561359313-0639aad49ff6?auto=format&fit=crop&w=1200&q=80",
    weather: "☀️ 26°C to 40°C", bestTime: "October to March (Navratri festivals draw massive crowds)",
    packing: "🧳 Traditional cotton clothes, comfortable walking shoes for hill shrines.",
    budget: "💰 Est. Budget: ₹1,200 - ₹3,000 / day",
    history_geo_political: "History: A sacred Shakti Peeth situated on the banks of River Ganga, where Goddess Vindhyavasini is worshipped.",
    picnic_spots: "🛕 Vindhyavasini Devi Temple\n🏛️ Ashtabhujadevi Temple & Kali Khoh Temple\n🌿 Sita Kund & Rameshwaram Temple\n🏞️ Ganga Ghats Vindhyachal",
    transport_roadmap: "Road Map: Connected via Mirzapur-Vindhyachal road. Transport: Vindhyachal Railway Station & Varanasi Airport (75 km).",
    hotels_booking: "🏨 Hotel Ganges View\n🏨 Vindhyachal Tourist Bungalow (UP Tourism)\n🏨 Local Pilgrim Lodges",
    markets_food: "🛍️ Temple Pathway Market.\n🍲 Banarasi Kachori, Local Sweets, Peda Prasad.",
    culture_helpline: "Culture: Shaktism and ritualistic heritage. Helpline: Police: 100 | SOS: 112"
  },
  "gorakhnath_gorakhpur": {
    Name: "Gorakhnath Temple - Historic Nath Peeth Shrine",
    City: "Gorakhpur", State: "Uttar Pradesh", Type: "🛕 Renowned Nath Sampradaya Temple",
    image_url: "https://images.unsplash.com/photo-1561359313-0639aad49ff6?auto=format&fit=crop&w=1200&q=80",
    weather: "🌤️ 24°C to 38°C", bestTime: "October to March (Makar Sankranti Mela is grand)",
    packing: "🧳 Traditional or modest clothing, comfortable footwear.",
    budget: "💰 Est. Budget: ₹1,500 - ₹3,500 / day",
    history_geo_political: "History: A prominent spiritual shrine dedicated to Guru Gorakhnath, representing the Nath monastic order and serving as a major cultural center in eastern UP.",
    picnic_spots: "🛕 Gorakhnath Temple Complex & Gorakhnath Samadhi\n🏛️ Vimanchal Park & Arogya Mandir\n🌿 Ramgarh Tal Lake (Boating & Waterfront)\n🏞️ Vinodbhanu Park",
    transport_roadmap: "Road Map: Well connected via NH-27 and NH-28. Transport: Gorakhpur Junction Railway Station & Gorakhpur Airport (GOP).",
    hotels_booking: "🏨 Radisson Blu Gorakhpur\n🏨 Hotel Marina Gorakhpur\n🏨 Hotel Bobina",
    markets_food: "🛍️ Golghar Market, Town Hall Bazaar.\n🍲 Gorakhpuri Local Sweets, Thandai, North Indian Delicacies.",
    culture_helpline: "Culture: Nath yogi spiritual tradition. Helpline: Police: 100 | SOS: 112"
  },
  "sankat_mochan_varanasi": {
    Name: "Sankat Mochan Hanuman Temple - Devotional Sanctuary",
    City: "Varanasi", State: "Uttar Pradesh", Type: "🛕 Sacred Hanuman Temple",
    image_url: "https://images.unsplash.com/photo-1561359313-0639aad49ff6?auto=format&fit=crop&w=1200&q=80",
    weather: "🌤️ 26°C to 38°C", bestTime: "October to March (Sankat Mochan Sangeet Samaroh is world famous)",
    packing: "🧳 Traditional clothing, comfortable footwear.",
    budget: "💰 Est. Budget: ₹1,500 - ₹3,500 / day",
    history_geo_political: "History: Founded by the medieval saint Tulsidas, this historic temple dedicated to Lord Hanuman is a major spiritual landmark in Varanasi.",
    picnic_spots: "🛕 Sankat Mochan Temple & Tulsi Manas Temple\n🏛️ Durga Kund Temple (Monkey Temple)\n🌿 BHU Campus & Vishwanath Temple\n🏞️ Assi Ghat Riverfront",
    transport_roadmap: "Road Map: Connected via Lanka-Durga Kund road. Transport: Varanasi Junction Railway Station & Varanasi Airport.",
    hotels_booking: "🏨 Hotel Taj Ganges\n🏨 BrijRama Palace\n🏨 Alka Hotel Varanasi",
    markets_food: "🛍️ Lanka Market, Godowlia Bazaar.\n🍲 Banarasi Kachori-Jalebi, Malaiyyo, Banarasi Paan.",
    culture_helpline: "Culture: Tulsidas devotional heritage. Helpline: Police: 100 | SOS: 112"
  },
  "bade_hanuman_prayagraj": {
    Name: "Bade Hanuman Temple (Lete Hue Hanuman) - Unique Sangam Shrine",
    City: "Prayagraj (Allahabad)", State: "Uttar Pradesh", Type: "🛕 Unique Reclining Hanuman Shrine",
    image_url: "https://images.unsplash.com/photo-1561359313-0639aad49ff6?auto=format&fit=crop&w=1200&q=80",
    weather: "🌤️ 25°C to 39°C", bestTime: "October to March (Magh Mela & Kumbh Mela hub)",
    packing: "🧳 Traditional clothing, comfortable walking footwear.",
    budget: "💰 Est. Budget: ₹1,500 - ₹3,500 / day",
    history_geo_political: "History: A unique underground temple housing a massive 20-foot reclining idol of Lord Hanuman, located near the holy Triveni Sangam.",
    picnic_spots: "🛕 Bade Hanuman Temple & Triveni Sangam\n🏛️ Allahabad Fort & Patalpuri Temple\n🌿 Anand Bhawan (Museum of Nehru family)\n🏞️ Chandrashekhar Azad Park (Company Garden)",
    transport_roadmap: "Road Map: Connected via NH-19 and NH-30. Transport: Prayagraj Junction & Prayagraj Airport (IXD).",
    hotels_booking: "🏨 Hotel Kanha Shyam\n🏨 Legend Hotel Prayagraj\n🏨 Hotel Milan Palace",
    markets_food: "🛍️ Civil Lines Market, Chowk Bazaar.\n🍲 Allahabad Guavas, Chaat, North Indian Thali.",
    culture_helpline: "Culture: Sangam holy confluence tradition. Helpline: Police: 100 | SOS: 112"
  },
  "patna_sahib": {
    Name: "Takht Sri Patna Sahib - Sacred Sikh Pilgrimage",
    City: "Patna", State: "Bihar", Type: "🕊️ Historic Gurudwara",
    image_url: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80",
    weather: "🌤️ 25°C to 37°C", bestTime: "October to March (Guru Gobind Singh Jayanti is grand)",
    packing: "🧳 Head covering (scarf/dupatta/handkerchief mandatory), modest clothing.",
    budget: "💰 Est. Budget: ₹1,500 - ₹3,500 / day",
    history_geo_political: "History: Birthplace of the tenth Sikh Guru, Guru Gobind Singh Ji. One of the five Takhts (seats of temporal authority) in Sikhism.",
    picnic_spots: "🛕 Takht Sri Patna Sahib Gurudwara\n🏛️ Golghar & Patna Museum\n🌿 Buddha Smriti Park\n🏞️ Marine Drive Patna ( Ganga Path)",
    transport_roadmap: "Road Map: Situated in Patna City area. Transport: Patna Sahib Railway Station, Rajendra Nagar Terminal & Jay Prakash Narayan International Airport (PAT).",
    hotels_booking: "🏨 Hotel Maurya Patna\n🏨 Lemon Tree Premier Patna\n🏨 Hotel Patliputra Ashok",
    markets_food: "🛍️ Maurya Lok Complex, Chowk Market.\n🍲 Authentic Bihari Litti Chokha, Sattu Paratha, Khaja of Silao.",
    culture_helpline: "Culture: Sikh heritage and community service (Langar). Helpline: Police: 100 | SOS: 112"
  },
  "mahabodhi_bodhgaya": {
    Name: "Mahabodhi Temple Bodh Gaya - Seat of Enlightenment",
    City: "Bodh Gaya", State: "Bihar", Type: "🛕 UNESCO World Heritage Buddhist Shrine",
    image_url: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80",
    weather: "🌤️ 24°C to 36°C", bestTime: "October to March",
    packing: "🧳 Modest comfortable clothing, slip-on footwear (shoes are prohibited inside temple complex area).",
    budget: "💰 Est. Budget: ₹1,800 - ₹4,000 / day",
    history_geo_political: "History: Ancient temple marking the location where Gautama Buddha attained enlightenment under the sacred Bodhi Tree.",
    picnic_spots: "🛕 Mahabodhi Temple Complex & Holy Bodhi Tree\n🏛️ Great Buddha Statue (80-foot statue)\n🌿 International Buddhist Monasteries (Thai, Japanese, Bhutanese temples)\n🏞️ Muchalinda Lake",
    transport_roadmap: "Road Map: Connected via NH-22. Transport: Gaya Junction Railway Station (13 km) & Gaya Airport (GAY).",
    hotels_booking: "🏨 The Bodhgaya Hotel Asoka\n🏨 Hotel Royal Residency\n🏨 Oaks Bodhgaya",
    markets_food: "🛍️ Tibetan Market Bodhgaya.\n🍲 Tibetan Thukpa, Momos, Bihari Thali, Sattu drink.",
    culture_helpline: "Culture: Global Buddhist peace heritage. Helpline: Police: 100 | SOS: 112"
  },
  "mangla_gauri_gaya": {
    Name: "Mangla Gauri Temple - Ancient Shakti Peeth of Gaya",
    City: "Gaya", State: "Bihar", Type: "🛕 Sacred Shakti Peeth",
    image_url: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80",
    weather: "🌤️ 25°C to 40°C", bestTime: "October to March (Pitru Paksha Mela is massive)",
    packing: "🧳 Traditional Indian attire, comfortable footwear for hill steps.",
    budget: "💰 Est. Budget: ₹1,200 - ₹3,000 / day",
    history_geo_political: "History: One of the ancient Shakti Peeths mentioned in holy scriptures, situated on Mangla Gauri hill in Gaya, revered for ancestral rituals (Shraddha).",
    picnic_spots: "🛕 Mangla Gauri Temple & Vishnupad Temple\n🏛️ Pretshila Hill & Ramshila Hill\n🌿 Falgu River Ghats\n🏞️ Bodh Gaya Temples (Nearby)",
    transport_roadmap: "Road Map: Connected via NH-22. Transport: Gaya Junction Railway Station & Gaya Airport.",
    hotels_booking: "🏨 Hotel Surya Gaya\n🏨 Hotel Royal Residency\n🏨 Hotel Riverside",
    markets_food: "🛍️ Gaya Town Market.\n🍲 Famous Gaya Tilkut, Anarsa, Bihari Litti Chokha.",
    culture_helpline: "Culture: Ancestral worship & Shakti devotion. Helpline: Police: 100 | SOS: 112"
  },
  "hariharnath_sonepur": {
    Name: "Hariharnath Temple Sonepur - Historic Hari-Hara Shrine",
    City: "Sonepur", State: "Bihar", Type: "🛕 Historic Vishnu-Shiva Shrine",
    image_url: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80",
    weather: "🌤️ 24°C to 37°C", bestTime: "November to December (Sonepur Cattle Fair season)",
    packing: "🧳 Simple traditional clothing, comfortable shoes.",
    budget: "💰 Est. Budget: ₹1,200 - ₹2,800 / day",
    history_geo_political: "History: Ancient temple at the confluence of Gandak and Ganga rivers, famous for the legend of Gajendra Moksha and host to Asia's largest cattle fair.",
    picnic_spots: "🛕 Hariharnath Temple Complex\n🏛️ Sonepur Cattle Fair Grounds (Mela Kshetra)\n🌿 Gandak River Ghats\n🏞️ Akauna Konch Ancient site",
    transport_roadmap: "Road Map: Connected via NH-19 near Hajipur. Transport: Sonepur Junction Railway Station & Patna Airport (25 km).",
    hotels_booking: "🏨 Hotel Vaishali Sonepur\n🏨 Local Tourist Cottages during Fair\n🏨 Hajipur Hotels",
    markets_food: "🛍️ Sonepur Mela Bazaar.\n🍲 Thekua, Litti Chokha, Traditional Bihari Sweets.",
    culture_helpline: "Culture: Mythological confluence heritage. Helpline: Police: 100 | SOS: 112"
  }
};
