export const MASTER_INDIA_TOURISM_DIRECTORY: Record<string, {
  Name: string;
  City: string;
  State: string;
  Type: string;
  image_url: string;
  weather: string;
  bestTime: string;
  packing: string;
  budget: string;
  history_geo_political: string;
  picnic_spots: string;
  transport_roadmap: string;
  hotels_booking: string;
  markets_food: string;
  culture_helpline: string;
}> = {
  "kedarnath": {
    Name: "Kedarnath Temple - Sacred Himalayan Shrine",
    City: "Kedarnath", State: "Uttarakhand", Type: "🛕 Char Dham & Jyotirlinga",
    image_url: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=1200&q=80",
    weather: "❄️ 5°C to 15°C (Cold)", bestTime: "May to June & September to October",
    packing: "🧳 Heavy woolens, thermal innerwear, trekking shoes, waterproof jacket, walking stick.",
    budget: "💰 Est. Budget: ₹3,000 - ₹6,000 / day",
    history_geo_political: "History: Built by the Pandavas and revived by Adi Shankaracharya in the 8th century. Situated near the Mandakini river.",
    picnic_spots: "🛕 Kedarnath Main Temple\n🏛️ Bhairavnath Temple\n🌿 Vasuki Tal Trek\n🏞️ Chorabari Glacier (Gandhi Sarovar)",
    transport_roadmap: "Road Map: Accessible via Gaurikund trek (16 km) or helicopter service from Phata/Sersi. Transport: Dehradun Airport (DED) & Rishikesh Railway Station.",
    hotels_booking: "🏨 GMVN Tourist Transit Camps\n🏨 Kedar Camp Resorts\n🏨 Local Pilgrim Cottages",
    markets_food: "🛍️ Kedarnath Base Market.\n🍲 Hot Maggi, Tea, Local Rajma Chawal, Satvik North Indian Thali.",
    culture_helpline: "Culture: Himalayan spiritual traditions. Helpline: Police: 100 | SOS: 112"
  },
  "badrinath": {
    Name: "Badrinath Temple - Abode of Lord Vishnu",
    City: "Badrinath", State: "Uttarakhand", Type: "🛕 Char Dham Pilgrimage",
    image_url: "https://images.unsplash.com/photo-1590736969955-71cc94901144?auto=format&fit=crop&w=1200&q=80",
    weather: "⛅ 8°C to 18°C (Chilly)", bestTime: "May to June & September to October",
    packing: "🧳 Heavy woolens, warm jackets, thermal layers, comfortable trekking shoes.",
    budget: "💰 Est. Budget: ₹2,500 - ₹5,500 / day",
    history_geo_political: "History: Re-established as a major holy shrine by Adi Shankaracharya in the 9th century, nestled between Nar and Narayan mountain ranges.",
    picnic_spots: "🛕 Badrinath Temple\n🏛️ Tapt Kund (Hot Sulphur Springs)\n🌿 Mana Village (Last village of India)\n🏞️ Vasudhara Falls & Charanpaduka",
    transport_roadmap: "Road Map: Connected via NH-7. Transport: Rishikesh Railway Station (295 km) & Dehradun Airport (315 km).",
    hotels_booking: "🏨 Sarovar Portico Badrinath\n🏨 Hotel Snow Crest\n🏨 GMVN Guest House Badrinath",
    markets_food: "🛍️ Badrinath Main Bazaar.\n🍲 North Indian Sattvic Food, Local Tea, Jalebi.",
    culture_helpline: "Culture: Vedic Vaishnavism. Helpline: Police: 100 | SOS: 112"
  },
  "gangotri": {
    Name: "Gangotri Dham - Origin of River Ganga",
    City: "Gangotri", State: "Uttarakhand", Type: "🛕 Char Dham Pilgrimage",
    image_url: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80",
    weather: "🌡️ 6°C to 17°C", bestTime: "May to June & September to October",
    packing: "🧳 Woolen clothes, windcheater, sturdy walking boots.",
    budget: "💰 Est. Budget: ₹2,000 - ₹4,500 / day",
    history_geo_political: "History: Dedicated to Goddess Ganga, built on the banks of Bhagirathi river where King Bhagirath worshipped Lord Shiva.",
    picnic_spots: "🛕 Gangotri Temple\n🏛️ Bhagirath Shila\n🌿 Gaumukh Glacier Trek (Source)\n🏞️ Subhidyal Waterfall",
    transport_roadmap: "Road Map: Connected via NH-34. Transport: Dehradun Airport (250 km) & Rishikesh Railway Station.",
    hotels_booking: "🏨 GMVN Tourist Rest House\n🏨 Hotel Bhagirathi\n🏨 Local Pilgrim Lodges",
    markets_food: "🛍️ Gangotri Market Square.\n🍲 Pure Vegetarian North Indian Meals, Hot Soups.",
    culture_helpline: "Culture: River goddess worship. Helpline: Police: 100 | SOS: 112"
  },
  "yamunotri": {
    Name: "Yamunotri Dham - Source of River Yamuna",
    City: "Yamunotri", State: "Uttarakhand", Type: "🛕 Char Dham Pilgrimage",
    image_url: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80",
    weather: "🌡️ 5°C to 16°C", bestTime: "May to June & September to October",
    packing: "🧳 Woolens, raincoat, trekking shoes, walking stick.",
    budget: "💰 Est. Budget: ₹2,000 - ₹4,500 / day",
    history_geo_political: "History: Westernmost shrine of the Garhwal Himalayas, dedicated to Goddess Yamuna, featuring natural thermal springs.",
    picnic_spots: "🛕 Yamunotri Temple\n🏛️ Surya Kund (Hot Water Spring)\n🌿 Divya Shila\n🏞️ Saptarishi Kund Trek",
    transport_roadmap: "Road Map: Accessible via Jankichatti trek (6 km). Transport: Dehradun Airport (180 km).",
    hotels_booking: "🏨 GMVN Yamunotri\n🏨 Hotel Yamuna Kriti\n🏨 Pilgrim Camps",
    markets_food: "🛍️ Jankichatti & Yamunotri Stalls.\n🍲 Local Tea, Potatoes boiled in Surya Kund, Simple Thali.",
    culture_helpline: "Culture: Himalayan ritual heritage. Helpline: Police: 100 | SOS: 112"
  },
  "somnath": {
    Name: "Somnath Temple - First Among Jyotirlingas",
    City: "Prabhas Patan (Veraval)", State: "Gujarat", Type: "🛕 First Jyotirlinga",
    image_url: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=1200&q=80",
    weather: "☀️ 32°C (Coastal Breeze)", bestTime: "October to March",
    packing: "🧳 Light cotton clothing, traditional wear for temple inner sanctum.",
    budget: "💰 Est. Budget: ₹2,000 - ₹4,500 / day",
    history_geo_political: "History: The first of the 12 Jyotirlinga shrines of Shiva. Rebuilt several times throughout history as a symbol of eternal faith.",
    picnic_spots: "🛕 Somnath Temple & Sound-Light Show\n🏛️ Bhalka Tirth (Lord Krishna's departure site)\n🌿 Triveni Sangam (Sea confluence)\n🏞️ Prabhas Patan Museum",
    transport_roadmap: "Road Map: Connected via NH-51. Transport: Veraval Railway Station (7 km) & Diu Airport (55 km).",
    hotels_booking: "🏨 The Fern Residency Somnath\n🏨 Lords Inn Somnath\n🏨 Hotel Somnath Sagar",
    markets_food: "🛍️ Somnath Temple Chowk.\n🍲 Gujarati Thali, Khaman, Ganthiya, Coconut Water.",
    culture_helpline: "Culture: Saurashtra cultural heritage. Helpline: Police: 100 | SOS: 112"
  },
  "mahakaleshwar": {
    Name: "Mahakaleshwar Ujjain - Shrine of Time & Power",
    City: "Ujjain", State: "Madhya Pradesh", Type: "🛕 Famous Jyotirlinga",
    image_url: "https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?auto=format&fit=crop&w=1200&q=80",
    weather: "🌤️ 25°C to 38°C", bestTime: "October to March (Sawan & Mahashivratri are grand)",
    packing: "🧳 Traditional dhoti/kurta for Bhasma Aarti, light cottons for day.",
    budget: "💰 Est. Budget: ₹1,800 - ₹4,000 / day",
    history_geo_political: "History: Ancient temple situated alongside the holy Kshipra river, famous worldwide for its unique Bhasma Aarti ritual.",
    picnic_spots: "🛕 Mahakaleshwar Jyotirlinga & Mahakal Lok Corridor\n🏛️ Harsiddhi Temple & Kal Bhairav Temple\n🌿 Ram Ghat (Kshipra River Aarti)\n🏞️ Sandipani Ashram",
    transport_roadmap: "Road Map: Connected via Indore-Ujjain highway. Transport: Ujjain Junction & Indore Airport (IDR, 55 km).",
    hotels_booking: "🏨 Hotel Anjushree Ujjain\n🏨 Hotel Imperial Grand\n🏨 Ujjain Darshan Hotel",
    markets_food: "🛍️ Mahakal Market, Freeganj.\n🍲 Malwa Poha, Bhutte ka Kees, Ujjaini Kachori.",
    culture_helpline: "Culture: Ancient Avanti spiritual traditions. Helpline: Police: 100 | SOS: 112"
  },
  "shirdi": {
    Name: "Shirdi Sai Baba Shrine - Home of Universal Faith",
    City: "Shirdi", State: "Maharashtra", Type: "🛕 Revered Spiritual Shrine",
    image_url: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=1200&q=80",
    weather: "🌤️ 28°C to 38°C", bestTime: "October to March",
    packing: "🧳 Simple traditional or comfortable casual clothing.",
    budget: "💰 Est. Budget: ₹1,500 - ₹3,500 / day",
    history_geo_political: "History: Sacred town where Saint Sai Baba lived and preached universal love, tolerance, and devotion.",
    picnic_spots: "🛕 Shri Sai Baba Sansthan Temple Complex\n🏛️ Dwarkamai Masjid & Chavadi\n🌿 Gurusthan & Sai Museum\n🏞️ Wet N Joy Water Park (Nearby)",
    transport_roadmap: "Road Map: Connected via Ahmednagar-Manmad highway. Transport: Sainagar Shirdi Railway Station & Shirdi Airport (SAG).",
    hotels_booking: "🏨 Sun-n-Sand Shirdi\n🏨 Hotel Sai Leela\n🏨 Marasa Sarovar Premiere Shirdi",
    markets_food: "🛍️ Temple Road Prasad Market.\n🍲 Maharashtrian Thali, Puran Poli, Laddoos.",
    culture_helpline: "Culture: Secular saint devotion. Helpline: Police: 100 | SOS: 112"
  },
  "tirupati": {
    Name: "Tirupati - Abode of Lord Venkateswara",
    City: "Tirupati", State: "Andhra Pradesh", Type: "🛕 Richest Spiritual Shrine",
    image_url: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80",
    weather: "☀️ 32°C (Warm)", bestTime: "September to March",
    packing: "🧳 Traditional Indian attire (Dhoti/Kurta for men, Saree/Salwar for women).",
    budget: "💰 Est. Budget: ₹2,000 - ₹4,500 / day",
    history_geo_political: "History: World-renowned temple town nestled in the Seshachalam Hills.",
    picnic_spots: "🛕 Sri Venkateswara Swami Temple (Tirumala Hills - The supreme and richest pilgrimage shrine in the world)\n🏛️ Govindaraja Swamy Temple & Alamelu Mangapuram (Tiruchanur)\n🌿 Sri Venkateswara Zoological Park & Silathoranam (Natural rock arch)\n🏞️ Akasaganga Waterfalls",
    transport_roadmap: "Road Map: Connected via NH-716. Transport: Tirupati Main Station & TIR Airport.",
    hotels_booking: "🏨 Fortune Select Grand Ridge\n🏨 Marasa Sarovar Premiere\n🏨 Hotel Bliss",
    markets_food: "🛍️ Tirumala Bazaar, Municipal Market.\n🍲 World famous Tirupati Laddu Prasadam, Andhra Meals.",
    culture_helpline: "Culture: Ancient Hindu devotional heritage. Helpline: Police: 100 | SOS: 112"
  },
  "rameswaram": {
    Name: "Rameshwaram - Sacred Island & Jyotirlinga",
    City: "Rameshwaram", State: "Tamil Nadu", Type: "🛕 Char Dham & Jyotirlinga",
    image_url: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80",
    weather: "☀️ 31°C (Tropical Coastal)", bestTime: "October to April",
    packing: "🧳 Light cotton clothes, traditional wear, extra pair of clothes for holy water bath (Theertham).",
    budget: "💰 Est. Budget: ₹2,000 - ₹4,000 / day",
    history_geo_political: "History: Sacred island town where Lord Rama built a bridge across the sea to Lanka. Home to Ramanathaswamy Temple featuring the longest corridor among Indian temples.",
    picnic_spots: "🛕 Ramanathaswamy Temple & 22 Holy Theerthams (Wells)\n🏛️ Pamban Bridge (India's first sea bridge)\n🌿 Dhanushkodi Beach & Ghost Town (End of the land)\n🏞️ Dr. A.P.J. Abdul Kalam Memorial",
    transport_roadmap: "Road Map: Connected via NH-87 and Pamban Bridge. Transport: Rameswaram Railway Station & Madurai Airport (170 km).",
    hotels_booking: "🏨 Hotel Tamil Nadu Rameswaram\n🏨 Daiwik Hotels Rameswaram\n🏨 Hotel Rameshwaram Grand",
    markets_food: "🛍️ Temple Car Street Bazaar, Fish market (for locals).\n🍲 South Indian Filter Coffee, Idli-Dosa, Chettinad Meals.",
    culture_helpline: "Culture: Ancient Dravidian temple architecture. Helpline: Police: 100 | SOS: 112"
  },
  "varanasi": {
    Name: "Varanasi (Kashi) - Spiritual Capital of India",
    City: "Varanasi", State: "Uttar Pradesh", Type: "🛕 Ancient Jyotirlinga City",
    image_url: "https://images.unsplash.com/photo-1561359313-0639aad49ff6?auto=format&fit=crop&w=1200&q=80",
    weather: "🌤️ 28°C to 38°C", bestTime: "October to March",
    packing: "🧳 Light cottons in summer, light woolens in winter, comfortable walking footwear.",
    budget: "💰 Est. Budget: ₹1,800 - ₹4,000 / day",
    history_geo_political: "History: One of the oldest living cities in the world, situated on the banks of River Ganga. Famous for Kashi Vishwanath Jyotirlinga and spiritual ghats.",
    picnic_spots: "🛕 Kashi Vishwanath Temple & Kashi Vishwanath Corridor\n🏛️ Dashashwamedh Ghat (Grand Ganga Aarti)\n🌿 Sarnath (Where Buddha gave his first sermon)\n🏞️ Assi Ghat & Boat Ride on River Ganges",
    transport_roadmap: "Road Map: Well connected via national highways. Transport: Varanasi Junction (BSB) & Lal Bahadur Shastri International Airport (VNS).",
    hotels_booking: "🏨 BrijRama Palace Varanasi\n🏨 Taj Ganges Varanasi\n🏨 Hotel Suryauday Haveli",
    markets_food: "🛍️ Godowla Chowk, Thatheri Bazaar.\n🍲 Banarasi Paan, Kachori Jalebi, Tamatar Chaat, Malaiyyo.",
    culture_helpline: "Culture: Ancient Hindu Vedic culture & classical arts. Helpline: Police: 100 | SOS: 112"
  },
  "khatushyam": {
    Name: "Khatu Shyam Ji - Abode of Shyam Baba",
    City: "Khatu", State: "Rajasthan", Type: "🛕 Devotional Shrine",
    image_url: "https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?auto=format&fit=crop&w=1200&q=80",
    weather: "☀️ 30°C to 40°C (Warm & Dry)", bestTime: "October to March (Falgun Mela is grand)",
    packing: "🧳 Traditional or comfortable cotton clothes, woolen stoles in winter.",
    budget: "💰 Est. Budget: ₹1,500 - ₹3,500 / day",
    history_geo_political: "History: Highly revered shrine dedicated to Barbarika (Shyam Baba), who is worshipped as an avatar of Krishna in Kaliyuga.",
    picnic_spots: "🛕 Khatu Shyam Ji Main Temple\n🏛️ Shyam Kund (Sacred pond)\n🌿 Shyam Vatika & Suraj Kund\n🏞️ Ringas Local Market",
    transport_roadmap: "Road Map: Connected via Jaipur-Bikaner highway. Transport: Ringas Junction (17 km) & Jaipur Airport (80 km).",
    hotels_booking: "🏨 Hotel Shyam Residency\n🏨 Shri Shyam Sarovar\n🏨 Local Pilgrim Dharamshalas",
    markets_food: "🛍️ Temple Street Bazaar.\n🍲 Rajasthani Dal Baati Churma, Peda Prasad, Mirchi Bada.",
    culture_helpline: "Culture: Marwari devotional traditions. Helpline: Police: 100 | SOS: 112"
  },
  "salasar": {
    Name: "Salasar Balaji - Shrine of Lord Hanuman",
    City: "Salasar", State: "Rajasthan", Type: "🛕 Sacred Hanuman Temple",
    image_url: "https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?auto=format&fit=crop&w=1200&q=80",
    weather: "☀️ 32°C (Dry & Warm)", bestTime: "October to March",
    packing: "🧳 Simple traditional clothing, comfortable footwear.",
    budget: "💰 Est. Budget: ₹1,500 - ₹3,000 / day",
    history_geo_political: "History: One of the most famous temples dedicated to Lord Hanuman, featuring a unique idol with a beard and mustache.",
    picnic_spots: "🛕 Salasar Balaji Main Temple\n🏛️ Anjani Mata Temple (Mother of Hanuman)\n🌿 Mohan Dham\n🏞️ Local Salasar Town Bazaar",
    transport_roadmap: "Road Map: Connected via Sujangarh-Salasar road. Transport: Sujangarh Railway Station (25 km).",
    hotels_booking: "🏨 Hotel Anjani\n🏨 Bhawani Niketan\n🏨 Local Dharamshalas",
    markets_food: "🛍️ Salasar Market.\n🍲 Besan Ke Gatte, Traditional Rajasthani Thali, Churma.",
    culture_helpline: "Culture: Rajasthani folk devotion. Helpline: Police: 100 | SOS: 112"
  },
  "pushkar_brahma": {
    Name: "Brahma Temple Pushkar - Unique Creator Shrine",
    City: "Pushkar", State: "Rajasthan", Type: "🛕 Rare Brahma Temple",
    image_url: "https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?auto=format&fit=crop&w=1200&q=80",
    weather: "🌤️ 25°C to 35°C", bestTime: "October to March (Pushkar Camel Fair time)",
    packing: "🧳 Light cottons, comfortable slip-on shoes for temple ghats.",
    budget: "💰 Est. Budget: ₹1,800 - ₹4,000 / day",
    history_geo_political: "History: One of the very few existing temples dedicated to Lord Brahma in the world, situated beside the holy Pushkar Lake.",
    picnic_spots: "🛕 Brahma Temple Pushkar\n🏛️ Pushkar Lake & Varaha Ghat (Evening Aarti)\n🌿 Savitri Temple (On Ratnagiri hill top)\n🏞️ Rangji Temple",
    transport_roadmap: "Road Map: Connected via Ajmer-Pushkar road. Transport: Ajmer Junction (15 km) & Kishangarh Airport (40 km).",
    hotels_booking: "🏨 The Westin Pushkar Resort & Spa\n🏨 Hotel Brahma Horizon\n🏨 Pushkar Bagh",
    markets_food: "🛍️ Brahma Temple Road Bazaar, Main Market.\n🍲 Malpua of Pushkar, Falooda, Cafe vegan food, Dal Baati.",
    culture_helpline: "Culture: Spiritual temple town vibe. Helpline: Police: 100 | SOS: 112"
  },
  "eklingji": {
    Name: "Eklingji Temple - Historic Deity of Mewar",
    City: "Kailashnagar (Udaipur)", State: "Rajasthan", Type: "🛕 Historic Shiva Temple",
    image_url: "https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?auto=format&fit=crop&w=1200&q=80",
    weather: "🌤️ 26°C to 36°C", bestTime: "September to March",
    packing: "🧳 Decent traditional clothing required inside the temple premises.",
    budget: "💰 Est. Budget: ₹2,000 - ₹4,500 / day",
    history_geo_political: "History: Double-storied magnificent temple complex built in 734 AD by Bappa Rawal, dedicated to Lord Shiva (Eklingji), the ruling deity of Mewar rulers.",
    picnic_spots: "🛕 Eklingji Temple Complex (108 temples inside)\n🏛️ Sas-Bahu Temples Nagda (Ancient ruins nearby)\n🌿 Baghela Lake view\n🏞️ Nagda Ancient Village",
    transport_roadmap: "Road Map: Located 22 km north of Udaipur on NH-8. Transport: Udaipur City Station & Maharana Pratap Airport (UDR).",
    hotels_booking: "🏨 Raffles Udaipur (Nearby)\n🏨 Aurika Udaipur\n🏨 Local Heritage Stays",
    markets_food: "🛍️ Nagda Road Stalls.\n🍲 Mewari Dal Baati, Mirchi Bada, Traditional Sweets.",
    culture_helpline: "Culture: Royal Mewar heritage. Helpline: Police: 100 | SOS: 112"
  },
  "mehandipur": {
    Name: "Mehandipur Balaji - Mystical Healing Shrine",
    City: "Mehandipur", State: "Rajasthan", Type: "🛕 Spiritual Exorcism & Faith Shrine",
    image_url: "https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?auto=format&fit=crop&w=1200&q=80",
    weather: "☀️ 32°C (Warm)", bestTime: "October to March",
    packing: "🧳 Simple traditional clothes, strict rules regarding prasad and temple rituals.",
    budget: "💰 Est. Budget: ₹1,200 - ₹3,000 / day",
    history_geo_political: "History: Prominent temple dedicated to Lord Hanuman, widely visited for spiritual healing and faith-based rituals.",
    picnic_spots: "🛕 Mehandipur Balaji Main Temple\n🏛️ Pret Raj Sarkar Temple\n🌿 Bhairav Ji Temple\n🏞️ Local Town Market",
    transport_roadmap: "Road Map: Situated on Jaipur-Agra National Highway-21. Transport: Bandikui Junction (35 km) & Jaipur Airport (95 km).",
    hotels_booking: "🏨 Hotel Balaji Darshan\n🏨 Pilgrim Guest Houses",
    markets_food: "🛍️ Balaji Chowk Market.\n🍲 Simple North Indian Sattvic Food, Boondi Prasad.",
    culture_helpline: "Culture: Faith-based spiritual customs. Helpline: Police: 100 | SOS: 112"
  },
  "dwarka": {
    Name: "Dwarkadhish Temple - Kingdom of Lord Krishna",
    City: "Dwarka", State: "Gujarat", Type: "🛕 Char Dham & Ancient Shrine",
    image_url: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=1200&q=80",
    weather: "☀️ 30°C (Coastal Breeze)", bestTime: "October to March",
    packing: "🧳 Light cotton clothing, traditional temple attire, sunglasses.",
    budget: "💰 Est. Budget: ₹2,000 - ₹4,500 / day",
    history_geo_political: "History: Ancient coastal city believed to be the legendary capital kingdom of Lord Krishna. One of the sacred Char Dhams.",
    picnic_spots: "🛕 Dwarkadhish Temple (Jagat Mandir)\n🏛️ Sudama Setu & Gomti Ghat\n🌿 Nageshwar Jyotirlinga (Nearby)\n🏞️ Bet Dwarka Island & Marine National Park",
    transport_roadmap: "Road Map: Connected via NH-51. Transport: Dwarka Railway Station & Jamnagar Airport (130 km).",
    hotels_booking: "🏨 Goverdhan Green Resort Dwarka\n🏨 Hotel Lord's Inn Dwarka\n🏨 Hotel Vraj Inn",
    markets_food: "🛍️ Dwarka Market Chowk.\n🍲 Gujarati Thali, Dhokla, Fafda, Sweets.",
    culture_helpline: "Culture: Coastal Saurashtra heritage. Helpline: Police: 100 | SOS: 112"
  },  "rajasthan_khatushyam": {
    Name: "Khatu Shyam Ji - Abode of Shyam Baba",
    City: "Khatu", State: "Rajasthan", Type: "🛕 Devotional Shrine",
    image_url: "https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?auto=format&fit=crop&w=1200&q=80",
    weather: "☀️ 30°C to 40°C (Warm & Dry)", bestTime: "October to March (Falgun Mela)",
    packing: "Traditional or comfortable cotton clothes, woolen stoles in winter.",
    budget: "₹1,500 - ₹3,500 / day",
    history_geo_political: "Highly revered shrine dedicated to Barbarika (Shyam Baba), worshipped as an avatar of Krishna in Kaliyuga.",
    picnic_spots: "🛕 Khatu Shyam Ji Main Temple\n🏛️ Shyam Kund (Sacred pond)\n🌿 Shyam Vatika & Suraj Kund\n🏞️ Ringas Local Market",
    transport_roadmap: "Connected via Jaipur-Bikaner highway. Ringas Junction (17 km) & Jaipur Airport (80 km).",
    hotels_booking: "Hotel Shyam Residency | Shri Shyam Sarovar | Dharamshalas",
    markets_food: "Temple Street Bazaar | Rajasthani Dal Baati Churma, Peda Prasad",
    culture_helpline: "Marwari traditions | Police: 100 | SOS: 112"
  },
  "rajasthan_salasar": {
    Name: "Salasar Balaji - Sacred Hanuman Temple",
    City: "Salasar", State: "Rajasthan", Type: "🛕 Sacred Hanuman Shrine",
    image_url: "https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?auto=format&fit=crop&w=1200&q=80",
    weather: "☀️ 32°C (Dry & Warm)", bestTime: "October to March",
    packing: "Simple traditional clothing, comfortable footwear.",
    budget: "₹1,500 - ₹3,000 / day",
    history_geo_political: "One of the most famous temples dedicated to Lord Hanuman, featuring a unique idol with a beard and mustache.",
    picnic_spots: "🛕 Salasar Balaji Main Temple\n🏛️ Anjani Mata Temple\n🌿 Mohan Dham\n🏞️ Salasar Town Bazaar",
    transport_roadmap: "Connected via Sujangarh-Salasar road. Sujangarh Railway Station (25 km).",
    hotels_booking: "Hotel Anjani | Bhawani Niketan | Pilgrim Guest Houses",
    markets_food: "Salasar Market | Besan Ke Gatte, Rajasthani Thali, Churma",
    culture_helpline: "Folk devotion | Police: 100 | SOS: 112"
  },
  "rajasthan_pushkar": {
    Name: "Brahma Temple & Holy Pushkar Lake",
    City: "Pushkar", State: "Rajasthan", Type: "🛕 Rare Brahma Shrine & Ghats",
    image_url: "https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?auto=format&fit=crop&w=1200&q=80",
    weather: "🌤️ 25°C to 35°C", bestTime: "October to March (Camel Fair)",
    packing: "Light cottons, comfortable slip-on shoes for temple ghats.",
    budget: "₹1,800 - ₹4,000 / day",
    history_geo_political: "One of the very few existing temples dedicated to Lord Brahma in the world, situated beside the holy Pushkar Lake.",
    picnic_spots: "🛕 Brahma Temple Pushkar\n🏛️ Pushkar Lake & Varaha Ghat (Evening Aarti)\n🌿 Savitri Temple (Ratnagiri Hill Top)\n🏞️ Rangji Temple",
    transport_roadmap: "Ajmer Junction (15 km) & Kishangarh Airport (40 km).",
    hotels_booking: "The Westin Pushkar Resort & Spa | Hotel Brahma Horizon",
    markets_food: "Brahma Temple Road Bazaar | Malpua of Pushkar, Falooda, Dal Baati",
    culture_helpline: "Spiritual town vibe | Police: 100 | SOS: 112"
  },
  "rajasthan_mehandipur": {
    Name: "Mehandipur Balaji - Mystical Faith Shrine",
    City: "Mehandipur", State: "Rajasthan", Type: "🛕 Spiritual Healing Shrine",
    image_url: "https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?auto=format&fit=crop&w=1200&q=80",
    weather: "☀️ 32°C (Warm)", bestTime: "October to March",
    packing: "Simple traditional clothes, strict rules regarding prasad and temple rituals.",
    budget: "₹1,200 - ₹3,000 / day",
    history_geo_political: "Prominent temple dedicated to Lord Hanuman, widely visited for spiritual healing and faith-based customs.",
    picnic_spots: "🛕 Mehandipur Balaji Main Temple\n🏛️ Pret Raj Sarkar Temple\n🌿 Bhairav Ji Temple\n🏞️ Local Town Market",
    transport_roadmap: "Jaipur-Agra National Highway-21. Bandikui Junction (35 km) & Jaipur Airport (95 km).",
    hotels_booking: "Hotel Balaji Darshan | Pilgrim Guest Houses",
    markets_food: "Balaji Chowk Market | Sattvic Food, Boondi Prasad",
    culture_helpline: "Faith customs | Police: 100 | SOS: 112"
  },
  "rajasthan_eklingji": {
    Name: "Eklingji Temple & Mewar Shrines",
    City: "Kailashnagar", State: "Rajasthan", Type: "🛕 Historic Shiva Temple & Palaces",
    image_url: "https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?auto=format&fit=crop&w=1200&q=80",
    weather: "🌤️ 26°C to 36°C", bestTime: "September to March",
    packing: "Decent traditional clothing required inside temple premises.",
    budget: "₹2,000 - ₹4,500 / day",
    history_geo_political: "Double-storied magnificent temple complex built in 734 AD by Bappa Rawal, dedicated to Lord Shiva, the ruling deity of Mewar rulers.",
    picnic_spots: "🛕 Eklingji Temple Complex (108 temples)\n🏛️ Sas-Bahu Temples Nagda (Ancient ruins)\n🌿 Baghela Lake view\n🏞️ Nagda Village",
    transport_roadmap: "Located 22 km north of Udaipur on NH-8. Udaipur City Station & Maharana Pratap Airport (UDR).",
    hotels_booking: "Raffles Udaipur | Aurika Udaipur | Heritage Stays",
    markets_food: "Nagda Road Stalls | Mewari Dal Baati, Mirchi Bada",
    culture_helpline: "Royal Mewar heritage | Police: 100 | SOS: 112"
  },
  "rajasthan_nathdwara": {
    Name: "Shrinathji Temple Nathdwara",
    City: "Nathdwara", State: "Rajasthan", Type: "🛕 Major Vaishnavite Shrine",
    image_url: "https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?auto=format&fit=crop&w=1200&q=80",
    weather: "🌤️ 25°C to 37°C", bestTime: "October to March (Annakoot festival)",
    packing: "Traditional or comfortable clothes, ethnic wear.",
    budget: "₹1,800 - ₹4,000 / day",
    history_geo_political: "Famous 17th-century temple housing the child form of Lord Krishna (Shrinathji), highly revered by Pushtimarg followers.",
    picnic_spots: "🛕 Shrinathji Main Temple\n🏛️ Charbhuja Temple & Dwarkadhish Temple (Kankroli)\n🌿 Banas River Bank\n🏞️ Statue of Belief (Vishwas Swaroopam - Tallest Shiva Statue)",
    transport_roadmap: "Connected via NH-8. Udaipur Airport (48 km) & Mavli Junction.",
    hotels_booking: "Justa Brijraj Vilas | Hotel Vallabh Darshan",
    markets_food: "Main Bazaar Nathdwara | Thandai, Pithore ki Sabzi, Traditional Sweets",
    culture_helpline: "Pushtimarg traditions | Police: 100 | SOS: 112"
  },
  "rajasthan_jaisalmer": {
    Name: "Jaisalmer Golden Fort & Desert Temples",
    City: "Jaisalmer", State: "Rajasthan", Type: "🏰 Golden Fort & Jain Temples",
    image_url: "https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?auto=format&fit=crop&w=1200&q=80",
    weather: "☀️ 24°C to 42°C", bestTime: "October to March",
    packing: "Light cottons, sunglasses, warm jackets for desert nights.",
    budget: "₹2,000 - ₹5,000 / day",
    history_geo_political: "Known as the Golden City, famous for its sandstone fort architecture, ancient Jain temples, and Thar desert safaris.",
    picnic_spots: "🛕 Ancient Jain Temples inside Jaisalmer Fort\n🏛️ Jaisalmer Fort (Golden Sonar Qila - Living Fort)\n🌿 Patwon ki Haveli & Salim Singh ki Haveli (Mahals)\n🏞️ Sam Sand Dunes (Desert Safari)",
    transport_roadmap: "Jaisalmer Airport (JSA) & Jaisalmer Railway Station.",
    hotels_booking: "Suryagarh Jaisalmer | WelcomHeritage Mohangarh Fort",
    markets_food: "Fort Market | Gatte ki Sabzi, Ker Sangri, Pyaaz Kachori",
    culture_helpline: "Desert Thar heritage | Police: 100 | SOS: 112"
  },  "rajasthan_khatushyam": {
    Name: "Khatu Shyam Ji - Abode of Shyam Baba",
    City: "Khatu", State: "Rajasthan", Type: "🛕 Devotional Shrine",
    image_url: "https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?auto=format&fit=crop&w=1200&q=80",
    weather: "☀️ 30°C to 40°C (Warm & Dry)", bestTime: "October to March (Falgun Mela)",
    packing: "Traditional or comfortable cotton clothes, woolen stoles in winter.",
    budget: "₹1,500 - ₹3,500 / day",
    history_geo_political: "Highly revered shrine dedicated to Barbarika (Shyam Baba), worshipped as an avatar of Krishna in Kaliyuga.",
    picnic_spots: "🛕 Khatu Shyam Ji Main Temple\n🏛️ Shyam Kund (Sacred pond)\n🌿 Shyam Vatika & Suraj Kund\n🏞️ Ringas Local Market",
    transport_roadmap: "Connected via Jaipur-Bikaner highway. Ringas Junction (17 km) & Jaipur Airport (80 km).",
    hotels_booking: "Hotel Shyam Residency | Shri Shyam Sarovar | Dharamshalas",
    markets_food: "Temple Street Bazaar | Rajasthani Dal Baati Churma, Peda Prasad",
    culture_helpline: "Marwari traditions | Police: 100 | SOS: 112"
  },
  "rajasthan_salasar": {
    Name: "Salasar Balaji - Sacred Hanuman Temple",
    City: "Salasar", State: "Rajasthan", Type: "🛕 Sacred Hanuman Shrine",
    image_url: "https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?auto=format&fit=crop&w=1200&q=80",
    weather: "☀️ 32°C (Dry & Warm)", bestTime: "October to March",
    packing: "Simple traditional clothing, comfortable footwear.",
    budget: "₹1,500 - ₹3,000 / day",
    history_geo_political: "One of the most famous temples dedicated to Lord Hanuman, featuring a unique idol with a beard and mustache.",
    picnic_spots: "🛕 Salasar Balaji Main Temple\n🏛️ Anjani Mata Temple\n🌿 Mohan Dham\n🏞️ Salasar Town Bazaar",
    transport_roadmap: "Connected via Sujangarh-Salasar road. Sujangarh Railway Station (25 km).",
    hotels_booking: "Hotel Anjani | Bhawani Niketan | Pilgrim Guest Houses",
    markets_food: "Salasar Market | Besan Ke Gatte, Rajasthani Thali, Churma",
    culture_helpline: "Folk devotion | Police: 100 | SOS: 112"
  },
  "rajasthan_pushkar": {
    Name: "Brahma Temple & Holy Pushkar Lake",
    City: "Pushkar", State: "Rajasthan", Type: "🛕 Rare Brahma Shrine & Ghats",
    image_url: "https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?auto=format&fit=crop&w=1200&q=80",
    weather: "🌤️ 25°C to 35°C", bestTime: "October to March (Camel Fair)",
    packing: "Light cottons, comfortable slip-on shoes for temple ghats.",
    budget: "₹1,800 - ₹4,000 / day",
    history_geo_political: "One of the very few existing temples dedicated to Lord Brahma in the world, situated beside the holy Pushkar Lake.",
    picnic_spots: "🛕 Brahma Temple Pushkar\n🏛️ Pushkar Lake & Varaha Ghat (Evening Aarti)\n🌿 Savitri Temple (Ratnagiri Hill Top)\n🏞️ Rangji Temple",
    transport_roadmap: "Ajmer Junction (15 km) & Kishangarh Airport (40 km).",
    hotels_booking: "The Westin Pushkar Resort & Spa | Hotel Brahma Horizon",
    markets_food: "Brahma Temple Road Bazaar | Malpua of Pushkar, Falooda, Dal Baati",
    culture_helpline: "Spiritual town vibe | Police: 100 | SOS: 112"
  },
  "rajasthan_mehandipur": {
    Name: "Mehandipur Balaji - Mystical Faith Shrine",
    City: "Mehandipur", State: "Rajasthan", Type: "🛕 Spiritual Healing Shrine",
    image_url: "https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?auto=format&fit=crop&w=1200&q=80",
    weather: "☀️ 32°C (Warm)", bestTime: "October to March",
    packing: "Simple traditional clothes, strict rules regarding prasad and temple rituals.",
    budget: "₹1,200 - ₹3,000 / day",
    history_geo_political: "Prominent temple dedicated to Lord Hanuman, widely visited for spiritual healing and faith-based customs.",
    picnic_spots: "🛕 Mehandipur Balaji Main Temple\n🏛️ Pret Raj Sarkar Temple\n🌿 Bhairav Ji Temple\n🏞️ Local Town Market",
    transport_roadmap: "Jaipur-Agra National Highway-21. Bandikui Junction (35 km) & Jaipur Airport (95 km).",
    hotels_booking: "Hotel Balaji Darshan | Pilgrim Guest Houses",
    markets_food: "Balaji Chowk Market | Sattvic Food, Boondi Prasad",
    culture_helpline: "Faith customs | Police: 100 | SOS: 112"
  },
  "rajasthan_eklingji": {
    Name: "Eklingji Temple & Mewar Shrines",
    City: "Kailashnagar", State: "Rajasthan", Type: "🛕 Historic Shiva Temple & Palaces",
    image_url: "https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?auto=format&fit=crop&w=1200&q=80",
    weather: "🌤️ 26°C to 36°C", bestTime: "September to March",
    packing: "Decent traditional clothing required inside temple premises.",
    budget: "₹2,000 - ₹4,500 / day",
    history_geo_political: "Double-storied magnificent temple complex built in 734 AD by Bappa Rawal, dedicated to Lord Shiva, the ruling deity of Mewar rulers.",
    picnic_spots: "🛕 Eklingji Temple Complex (108 temples)\n🏛️ Sas-Bahu Temples Nagda (Ancient ruins)\n🌿 Baghela Lake view\n🏞️ Nagda Village",
    transport_roadmap: "Located 22 km north of Udaipur on NH-8. Udaipur City Station & Maharana Pratap Airport (UDR).",
    hotels_booking: "Raffles Udaipur | Aurika Udaipur | Heritage Stays",
    markets_food: "Nagda Road Stalls | Mewari Dal Baati, Mirchi Bada",
    culture_helpline: "Royal Mewar heritage | Police: 100 | SOS: 112"
  },
  "rajasthan_nathdwara": {
    Name: "Shrinathji Temple Nathdwara",
    City: "Nathdwara", State: "Rajasthan", Type: "🛕 Major Vaishnavite Shrine",
    image_url: "https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?auto=format&fit=crop&w=1200&q=80",
    weather: "🌤️ 25°C to 37°C", bestTime: "October to March (Annakoot festival)",
    packing: "Traditional or comfortable clothes, ethnic wear.",
    budget: "₹1,800 - ₹4,000 / day",
    history_geo_political: "Famous 17th-century temple housing the child form of Lord Krishna (Shrinathji), highly revered by Pushtimarg followers.",
    picnic_spots: "🛕 Shrinathji Main Temple\n🏛️ Charbhuja Temple & Dwarkadhish Temple (Kankroli)\n🌿 Banas River Bank\n🏞️ Statue of Belief (Vishwas Swaroopam - Tallest Shiva Statue)",
    transport_roadmap: "Connected via NH-8. Udaipur Airport (48 km) & Mavli Junction.",
    hotels_booking: "Justa Brijraj Vilas | Hotel Vallabh Darshan",
    markets_food: "Main Bazaar Nathdwara | Thandai, Pithore ki Sabzi, Traditional Sweets",
    culture_helpline: "Pushtimarg traditions | Police: 100 | SOS: 112"
  },
  "rajasthan_jaisalmer": {
    Name: "Jaisalmer Golden Fort & Desert Temples",
    City: "Jaisalmer", State: "Rajasthan", Type: "🏰 Golden Fort & Jain Temples",
    image_url: "https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?auto=format&fit=crop&w=1200&q=80",
    weather: "☀️ 24°C to 42°C", bestTime: "October to March",
    packing: "Light cottons, sunglasses, warm jackets for desert nights.",
    budget: "₹2,000 - ₹5,000 / day",
    history_geo_political: "Known as the Golden City, famous for its sandstone fort architecture, ancient Jain temples, and Thar desert safaris.",
    picnic_spots: "🛕 Ancient Jain Temples inside Jaisalmer Fort\n🏛️ Jaisalmer Fort (Golden Sonar Qila - Living Fort)\n🌿 Patwon ki Haveli & Salim Singh ki Haveli (Mahals)\n🏞️ Sam Sand Dunes (Desert Safari)",
    transport_roadmap: "Jaisalmer Airport (JSA) & Jaisalmer Railway Station.",
    hotels_booking: "Suryagarh Jaisalmer | WelcomHeritage Mohangarh Fort",
    markets_food: "Fort Market | Gatte ki Sabzi, Ker Sangri, Pyaaz Kachori",
    culture_helpline: "Desert Thar heritage | Police: 100 | SOS: 112"
  },  "rajasthan_bikaner": {
    Name: "Bikaner Junagarh Fort & Karni Mata Temple",
    City: "Bikaner", State: "Rajasthan", Type: "🏰 Desert Forts & Rat Temple",
    image_url: "https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?auto=format&fit=crop&w=1200&q=80",
    weather: "☀️ 26°C to 44°C", bestTime: "October to March",
    packing: "Light cottons, sunglasses, warm shawls for winter desert nights.",
    budget: "₹1,500 - ₹3,500 / day",
    history_geo_political: "Founded in 1488 by Rao Bika, nestled in the Thar Desert. Famous for magnificent palaces, Havelis, and the unique Rat Temple.",
    picnic_spots: "🛕 Karni Mata Temple (Deshnoke - Rat Temple)\n🏛️ Junagarh Fort & Lalgarh Palace (Mahals)\n🌿 Bhandasar Jain Temple\n🏞️ Gajner Palace & Wildlife Sanctuary",
    transport_roadmap: "Bikaner Junction Railway Station & Jodhpur Airport (250 km).",
    hotels_booking: "Lalgarh Palace Hotel | Narendra Bhawan Bikaner",
    markets_food: "Kote Gate Market | Bikaneri Bhujia, Rasgulla, Dal Baati",
    culture_helpline: "Thar desert heritage | Police: 100 | SOS: 112"
  },
  "rajasthan_ranakpur": {
    Name: "Ranakpur Jain Temple & Aravali Valley",
    City: "Ranakpur (Pali)", State: "Rajasthan", Type: "🛕 Architectural Masterpiece",
    image_url: "https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?auto=format&fit=crop&w=1200&q=80",
    weather: "🌤️ 22°C to 36°C", bestTime: "October to March",
    packing: "Comfortable traditional clothing, walking footwear.",
    budget: "₹1,800 - ₹4,000 / day",
    history_geo_political: "World-renowned 15th-century Jain temple dedicated to Tirthankara Rishabhanatha, famous for its 1,444 intricately carved marble pillars.",
    picnic_spots: "🛕 Ranakpur Chaumukha Jain Temple\n🏛️ Sun Temple Ranakpur\n🌿 Kumbhalgarh Wildlife Sanctuary (Nearby)\n🏞️ Ranakpur Dam & Valley Views",
    transport_roadmap: "Falna Railway Station (30 km) & Udaipur Airport (90 km).",
    hotels_booking: "Fateh Bagh Ranakpur | King's Abode Ranakpur",
    markets_food: "Local Village Bazaar | Rajasthani Thali, Mirchi Vada",
    culture_helpline: "Aravali craft heritage | Police: 100 | SOS: 112"
  },
  "rajasthan_kumbhalgarh": {
    Name: "Kumbhalgarh Fort - Great Wall of India",
    City: "Kumbhalgarh", State: "Rajasthan", Type: "🏰 Massive Hill Fort & Mahals",
    image_url: "https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?auto=format&fit=crop&w=1200&q=80",
    weather: "🌤️ 20°C to 34°C", bestTime: "October to March",
    packing: "Comfortable trekking shoes, light woolens in evening.",
    budget: "₹1,800 - ₹4,000 / day",
    history_geo_political: "Birthplace of Maharana Pratap. Features the second-longest continuous wall in the world after the Great Wall of China.",
    picnic_spots: "🛕 Vedi Temple & Neelkanth Mahadev Temple\n🏛️ Kumbhalgarh Fort & Badal Mahal (Palace)\n🌿 Kumbhalgarh Wildlife Sanctuary\n🏞️ Parshuram Mahadev Cave Temple",
    transport_roadmap: "Falna Railway Station (50 km) & Udaipur Airport (85 km).",
    hotels_booking: "The Kumbha Bagh | Aodhi Hotel Kumbhalgarh",
    markets_food: "Fort base shops | Gatte ki Sabzi, Bajre ki Roti",
    culture_helpline: "Mewar history | Police: 100 | SOS: 112"
  },
  "rajasthan_alwar": {
    Name: "Alwar City Palace, Fort & Sariska Tiger Reserve",
    City: "Alwar", State: "Rajasthan", Type: "🏰 Historic Forts & Wildlife",
    image_url: "https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?auto=format&fit=crop&w=1200&q=80",
    weather: "☀️ 24°C to 40°C", bestTime: "October to March",
    packing: "Cotton clothing, camera, comfortable shoes.",
    budget: "₹1,500 - ₹3,500 / day",
    history_geo_political: "Gateway to Rajasthan from Delhi, famous for the haunted Bhangarh Fort, majestic Alwar City Palace, and Sariska Tigers.",
    picnic_spots: "🛕 Nilkanth Mahadev Temple\n🏛️ Bala Quila (Alwar Fort) & City Palace Mahal\n🌿 Sariska Tiger Reserve & Siliserh Lake Palace\n🏞️ Bhangarh Fort (Historic ruins)",
    transport_roadmap: "Alwar Junction Railway Station & Jaipur Airport (120 km).",
    hotels_booking: "Hotel Neemrana Fort-Palace | Alwar Bagh by Aamod",
    markets_food: "Alwar City Bazaar | Alwar ka Mawa (Kalakand), Dal Baati",
    culture_helpline: "Aravalli history | Police: 100 | SOS: 112"
  },  "rajasthan_bundi": {
    Name: "Bundi Palace, Stepwells & Taragarh Fort",
    City: "Bundi", State: "Rajasthan", Type: "🏰 Stepwells & Hill Forts",
    image_url: "https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?auto=format&fit=crop&w=1200&q=80",
    weather: "☀️ 24°C to 40°C", bestTime: "October to March",
    packing: "Light cottons, comfortable walking shoes.",
    budget: "₹1,500 - ₹3,500 / day",
    history_geo_political: "Famous for its ornate stepwells (Baoris), blue houses, massive Taragarh Fort, and exquisite Rajput mural paintings in Bundi Palace.",
    picnic_spots: "🛕 Rameshwara Mahadev Temple\n🏛️ Taragarh Fort & Bundi Palace (Mahals)\n🌿 Raniji ki Baori (Stepwell)\n🏞️ Sukh Mahal & Jait Sagar Lake",
    transport_roadmap: "Kota Railway Station (35 km) & Jaipur Airport (210 km).",
    hotels_booking: "Haveli Brabhat Niwas | Hotel Bundi Vilas",
    markets_food: "Main Bazaar Bundi | Rajasthani Dal Baati, Laal Maas, Local Sweets",
    culture_helpline: "Hadoti art heritage | Police: 100 | SOS: 112"
  },
  "rajasthan_kota": {
    Name: "Kota Palaces, Chambal Gardens & Temples",
    City: "Kota", State: "Rajasthan", Type: "🏰 Chambal River Palaces",
    image_url: "https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?auto=format&fit=crop&w=1200&q=80",
    weather: "☀️ 25°C to 42°C", bestTime: "October to March",
    packing: "Light cottons, sunglasses, walking shoes.",
    budget: "₹1,500 - ₹3,500 / day",
    history_geo_political: "Prominent industrial and coaching hub situated on the banks of Chambal River, featuring historic palaces, gardens, and ancient temples.",
    picnic_spots: "🛕 Mathadhish Temple (Patan Pol) & Garadia Mahadev Temple\n🏛️ Jag Mandir Palace (Chambal riverside)\n🌿 Chambal Gardens & Seven Wonders Park\n🏞️ Kota Barrage & Kishore Sagar Lake",
    transport_roadmap: "Kota Junction Railway Station & Jaipur Airport (240 km).",
    hotels_booking: "WelcomHeritage Umed Bhawan Palace | Hotel Surya Prime",
    markets_food: "Kota Shopping Center | Kota Kachori, Pyaaz Kachori, Ghevar",
    culture_helpline: "Hadoti heritage | Police: 100 | SOS: 112"
  },  "rajasthan_jaipur_complete": {
    Name: "Jaipur Comprehensive Heritage: Palaces, Temples & Picnic Spots",
    City: "Jaipur", State: "Rajasthan", Type: "🏰 Royal Mahals, Temples & Picnic Hub",
    image_url: "https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?auto=format&fit=crop&w=1200&q=80",
    weather: "☀️ 25°C to 42°C", bestTime: "October to March",
    packing: "Traditional or light cotton clothes, sunglasses, sun cap, comfortable walking shoes.",
    budget: "₹1,800 - ₹4,500 / day",
    history_geo_political: "Founded in 1727 by Maharaja Sawai Jai Singh II. The Pink City is a treasure trove of majestic Rajput architecture, grand forts, and spiritual landmarks.",
    picnic_spots: "🛕 Govind Dev Ji Temple, Birla Mandir & Galta Ji Temple (Monkey Temple)\n🏛️ Amber Fort, Nahargarh Fort & Jaigarh Fort\n🏰 City Palace & Hawa Mahal (Royal Mahals)\n🌿 Jal Mahal, Ram Niwas Garden & Sisodia Rani Garden\n🏞️ Patrika Gate (Jawahar Circle) & Amer Mahota Lake",
    transport_roadmap: "Jaipur International Airport (JAI) & Jaipur Junction. Well connected via national highways and expressways.",
    hotels_booking: "Rambagh Palace Jaipur | Fairmont Jaipur | Samode Haveli | Trident Jaipur",
    markets_food: "Johri Bazaar, Bapu Bazaar & Tripolia Bazaar | Dal Baati Churma, Pyaaz Kachori, Ghevar, Mirchi Bada",
    culture_helpline: "Rajputana royal heritage | Police: 100 | SOS: 112"
  }, "jaipur_picnic_jal_mahal": {
    Name: "Jal Mahal - The Water Palace",
    City: "Jaipur", State: "Rajasthan", Type: "🏞️ Scenic Picnic Spot",
    image_url: "https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?auto=format&fit=crop&w=1200&q=80",
    weather: "☀️ 25°C to 40°C", bestTime: "October to March",
    packing: "Light cottons, camera, sunglasses.",
    budget: "₹1,000 - ₹2,500 / day",
    history_geo_political: "An architectural marvel floating in the middle of Man Sagar Lake, built by Maharaja Madho Singh in the 18th century.",
    picnic_spots: "🏞️ Man Sagar Lake promenade\n🌿 Lakeside walking track\n📸 Scenic sunset and migratory bird watching point",
    transport_roadmap: "Located on Amer Road, easily accessible via auto, cab, or local bus from Jaipur city center.",
    hotels_booking: "Trident Jaipur | Hotel Clarks Amer",
    markets_food: "Lakeside food stalls | Local Chai, Chaat, Rajasthani Snacks",
    culture_helpline: "Pink City tourism | Police: 100 | SOS: 112"
  }, "jaipur_picnic_ram_niwas": {
    Name: "Ram Niwas Garden & Albert Hall",
    City: "Jaipur", State: "Rajasthan", Type: "🌿 Botanical Garden & Picnic Hub",
    image_url: "https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?auto=format&fit=crop&w=1200&q=80",
    weather: "☀️ 25°C to 40°C", bestTime: "October to March",
    packing: "Comfortable walking shoes, casual clothes.",
    budget: "₹1,000 - ₹2,500 / day",
    history_geo_political: "A massive 19th-century royal garden built by Maharaja Sawai Ram Singh II, housing the state museum and lush green lawns.",
    picnic_spots: "🌿 Lush green family lawns and shaded pathways\n🏛️ Albert Hall Museum (Central Museum)\n🎭 The Jawahar Kala Kendra & local cultural hubs nearby",
    transport_roadmap: "Located in the heart of Jaipur city near JLN Marg. Accessible via auto and cab.",
    hotels_booking: "Rambagh Palace | Hotel Apex International",
    markets_food: "Nearby Johri Bazaar | Pyaaz Kachori, Local Sweets",
    culture_helpline: "Local heritage | Police: 100 | SOS: 112"
  },"jaipur_picnic_sisodia_rani": {
    Name: "Sisodia Rani Garden & Palace",
    City: "Jaipur", State: "Rajasthan", Type: "🏰 Royal Garden Picnic Spot",
    image_url: "https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?auto=format&fit=crop&w=1200&q=80",
    weather: "☀️ 25°C to 42°C", bestTime: "October to March",
    packing: "Light ethnic or casual wear, sunglasses.",
    budget: "₹1,000 - ₹2,500 / day",
    history_geo_political: "Multi-tiered terraced garden built in 1728 by Maharaja Sawai Jai Singh II for his second queen, showcasing fountains, painted pavilions, and watercourses.",
    picnic_spots: "🌿 Multi-level terraced gardens with fountains\n🏰 Historic painted pavilions depicting Lord Krishna stories\n📸 Peaceful scenic photography spots",
    transport_roadmap: "Located 10 km on Jaipur-Agra National Highway. Accessible by taxi or auto.",
    hotels_booking: "Fairmont Jaipur | Treehouse Hotel",
    markets_food: "Agra Road local eateries | Dal Baati, Samosa, Tea",
    culture_helpline: "Rajputana heritage | Police: 100 | SOS: 112"
  },"jaipur_picnic_patrika_gate": {
    Name: "Patrika Gate & Jawahar Circle Garden",
    City: "Jaipur", State: "Rajasthan", Type: "📸 Architectural Landmark & Garden",
    image_url: "https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?auto=format&fit=crop&w=1200&q=80",
    weather: "☀️ 25°C to 40°C", bestTime: "October to March / Evening time",
    packing: "Stylish or casual clothes, camera for photoshoots.",
    budget: "₹1,000 - ₹2,500 / day",
    history_geo_political: "India's largest monumental gate located at Jawahar Circle, vibrant with hand-painted murals reflecting Rajasthani culture and history.",
    picnic_spots: "🏛️ Hand-painted colorful corridors of Patrika Gate\n🌿 Jawahar Circle landscaped rose garden\n⛲ Musical fountain show in the evening",
    transport_roadmap: "Located near Jaipur International Airport on Malviya Nagar Ring Road.",
    hotels_booking: "Marriott Jaipur | Hotel Clarks Amer",
    markets_food: "Malviya Nagar Markets | Street Food, Fast Food, South Indian",
    culture_helpline: "Modern Jaipur | Police: 100 | SOS: 112"
    },  "jaipur_picnic_kanota_dam": {
    Name: "Kanota Dam & Lake Reservoir",
    City: "Jaipur", State: "Rajasthan", Type: "🌊 Lakeside Picnic & Sunset Spot",
    image_url: "https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?auto=format&fit=crop&w=1200&q=80",
    weather: "☀️ 25°C to 40°C", bestTime: "October to March",
    packing: "Casual clothes, snacks, camera.",
    budget: "₹1,000 - ₹2,500 / day",
    history_geo_political: "A scenic water reservoir located on the outskirts of Jaipur towards Agra road, famous among locals as a quiet weekend picnic and sunset getaway.",
    picnic_spots: "🌊 Open water reservoir banks ideal for relaxing\n🌅 Breathtaking sunset views over the water\n📸 Quiet weekend hangout spot away from city rush",
    transport_roadmap: "Located off Agra Road, roughly 15-20 km from Jaipur main city center.",
    hotels_booking: "Narain Niwas Palace | Heritage Resorts",
    markets_food: "Agra Road Highway dhabas | Desi Chai, Pakoda, Local Meals",
    culture_helpline: "Outskirts leisure | Police: 100 | SOS: 112"
  },  "jaipur_picnic_smriti_van": {
    Name: "Smriti Van - Biodiversity & Nature Park",
    City: "Jaipur", State: "Rajasthan", Type: "🌿 Nature & Ecological Picnic Spot",
    image_url: "https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?auto=format&fit=crop&w=1200&q=80",
    weather: "☀️ 25°C to 40°C", bestTime: "October to March (Morning & Evening)",
    packing: "Comfortable walking shoes, sportswear, water bottle.",
    budget: "₹1,000 - ₹2,000 / day",
    history_geo_political: "A massive ecological and forestry park developed on the slopes of Jhalana hills, featuring diverse sections of trees, walking trails, and peace.",
    picnic_spots: "🌿 Tranquil walking and jogging trails through dense trees\n🐦 Bird watching spots and peaceful water ponds\n📸 Scenic nature photography locations",
    transport_roadmap: "Located near JLN Marg, opposite National Institute of Technology (MNIT), Jaipur.",
    hotels_booking: "Hotel Clarks Amer | Marriott Jaipur",
    markets_food: "Malviya Nagar local cafes | Healthy juices, Tea, Snacks",
    culture_helpline: "Eco tourism | Police: 100 | SOS: 112"
  },"jaipur_picnic_central_park": {
    Name: "Central Park Jaipur & National Flag",
    City: "Jaipur", State: "Rajasthan", Type: "🌳 City Park & Picnic Spot",
    image_url: "https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?auto=format&fit=crop&w=1200&q=80",
    weather: "☀️ 25°C to 40°C", bestTime: "October to March (Evening)",
    packing: "Casual clothes, walking shoes.",
    budget: "₹1,000 - ₹2,000 / day",
    history_geo_political: "The largest park in Jaipur city, built by the Jaipur Development Authority, featuring a massive national flag, musical fountain, and golf course.",
    picnic_spots: "⛲ Musical fountain show in the evenings\n🚩 Giant monumental National Flag installation\n🌿 Long green walking and running tracks for families",
    transport_roadmap: "Located right in the heart of the city near Prithviraj Road, C-Scheme.",
    hotels_booking: "Rambagh Palace | Hotel Madhuban",
    markets_food: "C-Scheme food outlets | Coffee, Fast Food, Local Delicacies",
    culture_helpline: "Urban leisure | Police: 100 | SOS: 112"
  },"jaipur_picnic_kanota_dam": {
    Name: "Kanota Dam & Lake Reservoir",
    City: "Jaipur", State: "Rajasthan", Type: "🌊 Lakeside Picnic & Sunset Spot",
    image_url: "https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?auto=format&fit=crop&w=1200&q=80",
    weather: "☀️ 25°C to 40°C", bestTime: "October to March",
    packing: "Casual clothes, snacks, camera.",
    budget: "₹1,000 - ₹2,500 / day",
    history_geo_political: "A scenic water reservoir located on the outskirts of Jaipur towards Agra road, famous among locals as a quiet weekend picnic and sunset getaway.",
    picnic_spots: "🌊 Open water reservoir banks ideal for relaxing\n🌅 Breathtaking sunset views over the water\n📸 Quiet weekend hangout spot away from city rush",
    transport_roadmap: "Located off Agra Road, roughly 15-20 km from Jaipur main city center.",
    hotels_booking: "Narain Niwas Palace | Heritage Resorts",
    markets_food: "Agra Road Highway dhabas | Desi Chai, Pakoda, Local Meals",
    culture_helpline: "Outskirts leisure | Police: 100 | SOS: 112"
  }, "gujarat_dwarka_completes": {
    Name: "Dwarka Kingdom, Temples & Coastal Spots",
    City: "Dwarka", State: "Gujarat", Type: "🛕 Ancient Char Dham & Coastal Hub",
    image_url: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=1200&q=80",
    weather: "☀️ 30°C (Coastal Breeze)", bestTime: "October to March",
    packing: "Light cotton clothing, traditional temple attire, sunglasses.",
    budget: "₹2,000 - ₹4,500 / day",
    history_geo_political: "Ancient coastal city believed to be the legendary capital kingdom of Lord Krishna. One of the sacred Char Dhams.",
    picnic_spots: "🛕 Dwarkadhish Temple (Jagat Mandir) & Nageshwar Jyotirlinga\n🏛️ Sudama Setu & Gomti Ghat\n🌿 Bet Dwarka Island & Marine National Park\n🏞️ Rukmini Devi Temple",
    transport_roadmap: "Connected via NH-51. Dwarka Railway Station & Jamnagar Airport (130 km).",
    hotels_booking: "Goverdhan Green Resort Dwarka | Hotel Lord's Inn Dwarka",
    markets_food: "Dwarka Market Chowk | Gujarati Thali, Dhokla, Fafda, Sweets",
    culture_helpline: "Coastal Saurashtra heritage | Police: 100 | SOS: 112"
  },"gujarat_statue_of_unity": {
    Name: "Statue of Unity & Kevadia Complex",
    City: "Kevadia (Ekta Nagar)", State: "Gujarat", Type: "🗿 World's Tallest Statue & Picnic Hub",
    image_url: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=1200&q=80",
    weather: "🌤️ 26°C to 38°C", bestTime: "October to March",
    packing: "Comfortable walking shoes, casual cottons, camera.",
    budget: "₹2,500 - ₹5,500 / day",
    history_geo_political: "World's tallest monument (182 meters) dedicated to Sardar Vallabhbhai Patel, surrounded by eco-tourism spots on Narmada river.",
    picnic_spots: "🗿 Statue of Unity Viewing Gallery & Laser Light Show\n🌿 Valley of Flowers & Cactus Garden\n🏞️ Sardar Sarovar Dam & Narmada Tent City\n🦁 Jungle Safari & Children Nutrition Park",
    transport_roadmap: "Ekta Nagar Railway Station (EKNR) & Vadodara Airport (90 km).",
    hotels_booking: "Tent City Narmada | Statue of Unity Kevadia Resorts",
    markets_food: "Ekta Food Court | Gujarati Thali, Kathiyawadi Food, Snacks",
    culture_helpline: "Unity heritage | Police: 100 | SOS: 112"
  }, "gujarat_ambaji": {
    Name: "Ambaji Shakti Peeth & Gabbar Hill",
    City: "Ambaji", State: "Gujarat", Type: "🛕 Sacred Shakti Peeth Shrine",
    image_url: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=1200&q=80",
    weather: "🌤️ 22°C to 35°C", bestTime: "October to March (Bhadra Purnima Mela)",
    packing: "Traditional or comfortable clothes, walking shoes.",
    budget: "₹1,500 - ₹3,500 / day",
    history_geo_political: "One of the 51 Shakti Peethas where the heart of Goddess Sati is believed to have fallen. Highly revered pilgrimage center.",
    picnic_spots: "🛕 Ambaji Mata Main Temple (No idol, sacred Visa Yantra)\n🏛️ Gabbar Hill Temple (Ropeway ride available)\n🌿 Mansarovar Lake near temple\n🏞️ Kamakshi Mandir & Shaktipith Darshan Park",
    transport_roadmap: "Abu Road Railway Station (20 km) & Ahmedabad Airport (180 km).",
    hotels_booking: "Circuit House Ambaji | Hotel Ambaji International",
    markets_food: "Ambaji Temple Bazaar | Mohanthal Prasad, Gujarati Snacks, Thali",
    culture_helpline: "Devotional heritage | Police: 100 | SOS: 112"
  },  "gujarat_gir_forest": {
    Name: "Gir National Park & Wildlife Sanctuary",
    City: "Sasangir", State: "Gujarat", Type: "🦁 Asiatic Lion Sanctuary & Nature Hub",
    image_url: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=1200&q=80",
    weather: "☀️ 25°C to 38°C", bestTime: "December to March (Safari Season)",
    packing: "Dull-colored safari clothing (khaki/green), binoculars, dust mask, comfortable boots.",
    budget: "₹2,500 - ₹6,500 / day",
    history_geo_political: "The only natural habitat in the world where the majestic Asiatic Lions roam free, established as a protected sanctuary in 1965.",
    picnic_spots: "🦁 Gir Jungle Safari (Open jeep wildlife tours)\n🏛️ Devalia Safari Park (Interpretation Zone)\n🌿 Kamleshwar Dam (Riverside picnic & crocodile viewing)\n🏞️ Kankai Mata Temple inside deep forest",
    transport_roadmap: "Veraval Railway Station (40 km) & Diu Airport (65 km). Well connected via road.",
    hotels_booking: "The Fern Gir Forest Resort | Woods at Sasan | Gir Birding Lodge",
    markets_food: "Sasangir Local Bazaar | Kathiyawadi Meals, Bajra Roti, Sev Tamatar",
    culture_helpline: "Wildlife conservation | Police: 100 | SOS: 112"
  },"gujarat_champaner_pavagadh": {
    Name: "Champaner-Pavagadh Archaeological Park",
    City: "Pavagadh", State: "Gujarat", Type: "🏰 UNESCO Forts & Shakti Peeth Temple",
    image_url: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=1200&q=80",
    weather: "🌤️ 24°C to 39°C", bestTime: "October to March",
    packing: "Comfortable trekking shoes, cotton clothing, camera.",
    budget: "₹1,800 - ₹4,000 / day",
    history_geo_political: "A UNESCO World Heritage Site featuring ancient Hindu and Islamic architecture, massive fort walls, palaces, and the sacred Kalika Mata Temple on top of Pavagadh hill.",
    picnic_spots: "🛕 Kalika Mata Temple Pavagadh (Hilltop Shakti Peeth via Ropeway)\n🏛️ Champaner Fort Ruins & Royal Palaces (Mahals)\n🌿 Jama Masjid & Kevada Masjid (Historic architecture)\n🏞️ Pavagadh Hill nature viewpoints and waterfalls",
    transport_roadmap: "Vadodara Junction (50 km) & Vadodara Airport (BDQ).",
    hotels_booking: "Champaner Heritage Resort | Hotel Pavagadh International",
    markets_food: "Pavagadh Hill base market | Gujarati Snacks, Fafda, Chai",
    culture_helpline: "UNESCO heritage | Police: 100 | SOS: 112"
  },"gujarat_kutch_white_rann": {
    Name: "Great Rann of Kutch & Cultural Hub",
    City: "Bhuj", State: "Gujarat", Type: "✨ White Salt Desert & Royal Palaces",
    image_url: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=1200&q=80",
    weather: "☀️ 12°C to 36°C (Cool nights, warm days)", bestTime: "November to February (Rann Utsav)",
    packing: "Warm jackets for cold desert nights, sunglasses, traditional or casual wear.",
    budget: "₹2,500 - ₹7,000 / day",
    history_geo_political: "A vast expanse of white salt desert that transforms into a magical cultural wonderland during the winter Rann Utsav, surrounded by historic palaces.",
    picnic_spots: "✨ White Rann Salt Desert (Moonlight view & Camel safari)\n🏛️ Aina Mahal & Prag Mahal (Royal Palaces in Bhuj)\n🌿 Kalo Dungar (Black Hill - Highest point of Kutch)\n🏞️ Dholavira (Ancient Indus Valley Civilization site)",
    transport_roadmap: "Bhuj Airport (BHJ) & Bhuj Railway Station. Well connected via highways.",
    hotels_booking: "Rann Utsav Tent City Dhordo | Regenta Resort Bhuj",
    markets_food: "Bhujodi Village & Mandvi Beach markets | Kutchi Dabeli, Pakwan, Kutchi Thali",
    culture_helpline: "Kutch handicraft heritage | Police: 100 | SOS: 112"
  },  "gujarat_modhera_sun_temple": {
    Name: "Modhera Sun Temple & Rani ki Vav",
    City: "Modhera & Patan", State: "Gujarat", Type: "🛕 Ancient Sun Shrine & UNESCO Stepwell",
    image_url: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=1200&q=80",
    weather: "☀️ 26°C to 41°C", bestTime: "October to March",
    packing: "Light cottons, sunglasses, comfortable walking shoes.",
    budget: "₹1,500 - ₹3,500 / day",
    history_geo_political: "Architectural marvels built in the 11th century by the Solanki dynasty. Modhera is dedicated to the Sun God, and Rani ki Vav is an underground stepwell masterpiece.",
    picnic_spots: "🛕 Modhera Sun Temple & Surya Kund step tank\n🏛️ Rani ki Vav (UNESCO World Heritage Stepwell in Patan)\n🌿 Sahastralinga Talav historic water tank\n🏞️ Patan Patola heritage weaving centers",
    transport_roadmap: "Connected via state highways. Mehsana Railway Station (25 km) & Ahmedabad Airport (100 km).",
    hotels_booking: "Hotel Tulsi Modhera | The Fern Mehsana",
    markets_food: "Patan Local Bazaar | Patan ni Ghari sweets, Gujarati Thali, Fafda",
    culture_helpline: "Solanki architecture | Police: 100 | SOS: 112"
  },"gujarat_becharaji": {
    Name: "Bahuchara Mata Temple Becharaji",
    City: "Becharaji", State: "Gujarat", Type: "🛕 Sacred Shakti Peeth Shrine",
    image_url: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=1200&q=80",
    weather: "☀️ 28°C to 40°C", bestTime: "October to March",
    packing: "Traditional temple clothing, comfortable footwear.",
    budget: "₹1,200 - ₹3,000 / day",
    history_geo_political: "One of the most revered Shakti shrines in Gujarat, dedicated to Goddess Bahuchara Mata, drawing lakhs of devotees every year.",
    picnic_spots: "🛕 Bahuchara Mata Main Temple & Sanctum\n🏛️ Shankhalapur Vada Mandir nearby\n🌿 Local town gardens and heritage spots\n🏞️ Becharaji Town Market",
    transport_roadmap: "Becharaji Railway Station & Ahmedabad Airport (90 km). Accessible via Kadi-Becharaji road.",
    hotels_booking: "Dharamshalas & Local Pilgrim Guest Houses",
    markets_food: "Becharaji Market | Traditional Prasad, Gujarati Snacks, Fafda Jalebi",
    culture_helpline: "Devotional traditions | Police: 100 | SOS: 112"
  },  "gujarat_junagadh_girnar": {
    Name: "Junagadh Girnar Mountain & Historic Forts",
    City: "Junagadh", State: "Gujarat", Type: "🛕 Sacred Mountain & Ancient Fort",
    image_url: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=1200&q=80",
    weather: "🌤️ 24°C to 38°C", bestTime: "October to March (Girnar Parikrama)",
    packing: "Comfortable trekking shoes, walking stick, light woolens for early morning.",
    budget: "₹1,500 - ₹4,000 / day",
    history_geo_political: "Historic city nestled at the foothills of Mount Girnar. Sacred to both Hindus and Jains, featuring ancient rock-cut edicts of Emperor Ashoka.",
    picnic_spots: "🛕 Girnar Jain Temples & Ambaji Temple (Hilltop peaks via Ropeway/Steps)\n🏛️ Uparkot Fort & Buddhist Caves (Ancient Mahals)\n🌿 Damodar Kund (Sacred bathing ghat)\n🏞️ Mahabat Maqbara (Architectural masterpiece mausoleum)",
    transport_roadmap: "Junagadh Junction Railway Station & Rajkot Airport (100 km).",
    hotels_booking: "Hotel Harmony Junagadh | Bellevue Sarovar Portico",
    markets_food: "Diwan Chowk Market | Gujarati Thali, Ganthiya, Puran Poli",
    culture_helpline: "Saurashtra history | Police: 100 | SOS: 112"
  },"gujarat_porbandar": {
    Name: "Porbandar Kirti Mandir & Coastal Shrines",
    City: "Porbandar", State: "Gujarat", Type: "🏛️ Mahatma Gandhi Birthplace & Beach",
    image_url: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=1200&q=80",
    weather: "☀️ 28°C to 35°C (Coastal)", bestTime: "October to March",
    packing: "Light cottons, sunglasses, beach wear.",
    budget: "₹1,500 - ₹3,500 / day",
    history_geo_political: "Birthplace of Mahatma Gandhi (Father of the Nation) and Sudama (friend of Lord Krishna), featuring historic memorials and clean sea beaches.",
    picnic_spots: "🏛️ Kirti Mandir (Gandhi's ancestral home memorial)\n🛕 Sudama Temple (Dedicated to Lord Krishna's friend)\n🌿 Porbandar Chowpatty Beach & Bird Sanctuary\n🏞️ Huzoor Palace (Royal seaside palace)",
    transport_roadmap: "Porbandar Airport (PBD) & Porbandar Railway Station.",
    hotels_booking: "Lords Inn Porbandar | Hotel Manish Palace",
    markets_food: "MG Road Bazaar | Porbandar Dabeli, Khaman, Fresh Seafood",
    culture_helpline: "Coastal heritage | Police: 100 | SOS: 112"
  },"gujarat_palitana": {
    Name: "Palitana Shatrunjaya Jain Temples Hill",
    City: "Palitana", State: "Gujarat", Type: "🛕 World's Largest Jain Temple City",
    image_url: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=1200&q=80",
    weather: "🌤️ 25°C to 38°C", bestTime: "October to March",
    packing: "Comfortable walking shoes, modest white/cotton clothes, water bottle.",
    budget: "₹1,500 - ₹3,500 / day",
    history_geo_political: "The world's only mountain with more than 800 marble temples, beautifully carved and perched on top of Shatrunjaya hill.",
    picnic_spots: "🛕 Shatrunjaya Hill Temple Complex (Over 800 marble Jain temples)\n🏛️ Adinath Temple (Main shrine)\n🌿 Taleti garden area at hill base\n🏞️ Shetrunjaya River banks",
    transport_roadmap: "Bhavnagar Airport (50 km) & Palitana Railway Station.",
    hotels_booking: "Vijay Mahgiri Hotel | Shreyas Hotel Palitana",
    markets_food: "Palitana Town Bazaar | Gujarati Shuddh Shakahari Thali, Fafda",
    culture_helpline: "Jain pilgrimage | Police: 100 | SOS: 112"
  },  "gujarat_surat": {
    Name: "Surat Diamond City, Fort & Coastal Beaches",
    City: "Surat", State: "Gujarat", Type: "🏙️ Commercial City, Fort & Beaches",
    image_url: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=1200&q=80",
    weather: "☀️ 28°C to 38°C (Humid coastal)", bestTime: "October to March",
    packing: "Light breathable cotton clothes, sunglasses.",
    budget: "₹2,000 - ₹4,500 / day",
    history_geo_political: "Famous globally as the Diamond and Textile Hub of India, situated on the banks of Tapi river with rich maritime and royal history.",
    picnic_spots: "🛕 Ambika Niketan Temple & ISKCON Temple Surat\n🏛️ Surat Castle (Old Fort) & Dutch Garden\n🌿 Dumas Beach & Suvali Beach\n🏞️ Sarthana Nature Park & Zoo",
    transport_roadmap: "Surat Airport (STV) & Surat Railway Station. Well connected via NH-48.",
    hotels_booking: "The Oberoi / Surat Marriott Hotel | Hotel Taj Gateway",
    markets_food: "Ring Road & Chowpati Market | Surti Locho, Undhiyu, Ghari Sweets",
    culture_helpline: "Surti culture | Police: 100 | SOS: 112"
  },
  "gujarat_vadodara": {
    Name: "Vadodara Laxmi Vilas Palace & Gardens",
    City: "Vadodara", State: "Gujarat", Type: "🏰 Royal Palaces & Cultural Hub",
    image_url: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=1200&q=80",
    weather: "☀️ 26°C to 40°C", bestTime: "October to March",
    packing: "Light cottons, comfortable walking shoes.",
    budget: "₹1,800 - ₹4,000 / day",
    history_geo_political: "Cultural capital of Gujarat, formerly known as Baroda, ruled by the Gaekwad dynasty. Famous for grand palaces and art galleries.",
    picnic_spots: "🛕 EME Temple (Unique geodesic dome temple) & Kirti Mandir\n🏛️ Laxmi Vilas Palace (Four times the size of Buckingham Palace - Royal Mahal)\n🌿 Sayaji Gardens & Zoo (Kamati Baug)\n🏞️ Sursagar Lake (Floating Shiva Statue)",
    transport_roadmap: "Vadodara Airport (BDQ) & Vadodara Junction Railway Station.",
    hotels_booking: "WelcomHotel Vadodara | Surya Palace",
    markets_food: "Mandvi Market | Sev Usal, Gujarati Thali, Bhakharwadi",
    culture_helpline: "Gaekwad heritage | Police: 100 | SOS: 112"
  },
  "gujarat_rajkot": {
    Name: "Rajkot Mahatma Gandhi Museum & Palaces",
    City: "Rajkot", State: "Gujarat", Type: "🏛️ Saurashtra Cultural Hub & Memorials",
    image_url: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=1200&q=80",
    weather: "☀️ 25°C to 41°C", bestTime: "October to March",
    packing: "Light cotton clothing, sunglasses.",
    budget: "₹1,500 - ₹3,500 / day",
    history_geo_political: "Heart of Saurashtra region, historically significant as the childhood residence and schooling place of Mahatma Gandhi.",
    picnic_spots: "🛕 Ramakrishna Ashram & Swaminarayan Temple Rajkot\n🏛️ Kaba Gandhi No Delo (Gandhi's childhood home museum)\n🌿 Watson Museum & Alfred High School\n🏞️ Aji Dam & Jubilee Garden",
    transport_roadmap: "Rajkot International Airport (Hirasar) & Rajkot Junction.",
    hotels_booking: "Fortune Hotel Park | The Imperial Palace Rajkot",
    markets_food: "Yagnik Road Market | Rajkot Chwanu, Ganthiya, Kathiyawadi Thali",
    culture_helpline: "Saurashtra spirit | Police: 100 | SOS: 112"
  },
  "gujarat_gandhinagar": {
    Name: "Gandhinagar Akshardham & Capital Gardens",
    City: "Gandhinagar", State: "Gujarat", Type: "🛕 Grand Spiritual Architecture & Parks",
    image_url: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=1200&q=80",
    weather: "☀️ 26°C to 40°C", bestTime: "October to March",
    packing: "Modest comfortable clothes for temple, walking shoes.",
    budget: "₹1,800 - ₹4,000 / day",
    history_geo_political: "Planned green capital city of Gujarat, located on the banks of Sabarmati river, named after Mahatma Gandhi.",
    picnic_spots: "🛕 Swaminarayan Akshardham Temple Complex & Water Show\n🏛️ Sarita Udyan & Indroda Nature Park (Dinosaur & Fossil Park)\n🌿 Punit Van (Botanical garden)\n🏞️ Sabarmati Riverfront promenade stretches",
    transport_roadmap: "Sardar Vallabhbhai Patel International Airport Ahmedabad (15 km away) & Gandhinagar Capital Station.",
    hotels_booking: "Gift City Club - The Club | The Leela Gandhinagar",
    markets_food: "Sector 21 Market | Gujarati Fast Food, Fafda Jalebi, Thali",
    culture_helpline: "Capital administration | Police: 100 | SOS: 112"
  },  "gujarat_shamlaji": {
    Name: "Shamlaji Ancient Temple & Tribal Heritage",
    City: "Shamlaji (Aravalli)", State: "Gujarat", Type: "🛕 Ancient Vaishnavite Shrine & Art",
    image_url: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=1200&q=80",
    weather: "🌤️ 24°C to 38°C", bestTime: "October to March (Kartik Purnima Fair)",
    packing: "Traditional or comfortable clothes, walking shoes.",
    budget: "₹1,200 - ₹3,000 / day",
    history_geo_political: "Renowned 11th-century architectural temple dedicated to Lord Krishna (Shamlaji), nestled on the Meshwo river banks surrounded by Aravalli hills.",
    picnic_spots: "🛕 Shamlaji Vishnu Temple (Black stone architecture)\n🏛️ Meshwo Reservoir and Dam site\n🌿 Devani Mori Buddhist archaeological site nearby\n🏞️ Aravalli forest nature trails",
    transport_roadmap: "Connected via NH-8. Himmatnagar Railway Station (45 km) & Ahmedabad Airport (125 km).",
    hotels_booking: "Local Pilgrim Guest Houses | Hotels in Himmatnagar",
    markets_food: "Shamlaji Bazaar | Traditional Prasad, Gujarati Thali, Snacks",
    culture_helpline: "Tribal heritage | Police: 100 | SOS: 112"
  },
  "gujarat_dakor": {
    Name: "Dakor Ranchhodraiji Maharaj Temple",
    City: "Dakor", State: "Gujarat", Type: "🛕 Famous Krishna Pilgrimage",
    image_url: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=1200&q=80",
    weather: "☀️ 26°C to 40°C", bestTime: "October to March (Poonam festivals)",
    packing: "Traditional temple attire, comfortable footwear.",
    budget: "₹1,200 - ₹3,000 / day",
    history_geo_political: "One of the most prominent pilgrimage centers in Gujarat dedicated to Lord Krishna as Ranchhodraiji, attracting lakhs of devotees every full moon.",
    picnic_spots: "🛕 Ranchhodraiji Main Temple Complex\n🏛️ Gomti Lake Ghats and temples around water\n🌿 Dakor town heritage walks\n🏞️ Local Gota and Prasad stalls area",
    transport_roadmap: "Dakor Railway Station & Vadodara Airport (55 km). Connected via state highways.",
    hotels_booking: "Dakor Temple Trust Guest House | Local Lodges",
    markets_food: "Temple Road Market | Dakor Gota, Sev Mamra, Peda Prasad",
    culture_helpline: "Bhakti traditions | Police: 100 | SOS: 112"
  },
  "gujarat_taranga_hill": {
    Name: "Taranga Hill Jain Temples & Sanctuary",
    City: "Taranga (Mehsana)", State: "Gujarat", Type: "🛕 Hilltop Jain Architecture",
    image_url: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=1200&q=80",
    weather: "🌤️ 22°C to 36°C", bestTime: "October to March",
    packing: "Comfortable trekking or walking shoes, light woolens for winter mornings.",
    budget: "₹1,500 - ₹3,500 / day",
    history_geo_political: "A historic hilltop pilgrimage center featuring magnificent 12th-century Jain temples built by King Kumarapala, showcasing supreme marble artistry.",
    picnic_spots: "🛕 Taranga Jain Temple Complex (Hilltop white marble architecture)\n🏛️ Ajitnath Temple\n🌿 Jogida Caves and surrounding hill viewpoints\n🏞️ Taranga forest wildlife range",
    transport_roadmap: "Taranga Hill Railway Station & Ahmedabad Airport (110 km).",
    hotels_booking: "Taranga Jain Dharamshala | Resorts near Visnagar",
    markets_food: "Temple Base Stalls | Shuddh Shakahari Snacks, Thali, Chai",
    culture_helpline: "Solanki architecture | Police: 100 | SOS: 112"
  }
};

